// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatMessage {
    "role": string;
    "content": any;
    "tool_call_id"?: string;
    "tool_calls"?: ToolCall[] | null;
}

export interface ChatRequest {
    "model": string;
    "messages": ChatMessage[] | null;
    "temperature": number;
    "max_tokens": number;
    "tools"?: ToolSchema[] | null;
}

export interface ToolCall {
    "id": string;
    "type": string;
    "function": ToolCallFunc;
}

export interface ToolCallFunc {
    "name": string;
    "arguments": string;
}

export interface ToolFunction {
    "name": string;
    "description": string;
    "parameters": any;
}

/**
 * ToolSchema 表示一个 LLM 函数调用工具（OpenAI function_calling 格式）。
 */
export interface ToolSchema {
    "type": string;
    "function": ToolFunction;
}
