// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatMessage {
    "role": string;
    "content": string;
}

export interface ChatRequest {
    "model": string;
    "messages": ChatMessage[] | null;
    "temperature": number;
    "max_tokens": number;
}
