// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatMessage {
    "role": string;
    "content": string;
}

export interface ChatRequest {
    "model": string;
    "messages": ChatMessage[] | null;
    "temperature": number;
    "max_tokens": number;
    "tools"?: ToolSchema[] | null;
}

export interface ToolFunction {
    "name": string;
    "description": string;
    "parameters": any;
}

/**
 * ToolSchema 表示一个 LLM 函数调用工具（OpenAI function_calling 格式）。
 */
export interface ToolSchema {
    "type": string;
    "function": ToolFunction;
}
