// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCustomSoftware adds a user-defined software entry to the config.
 * @param {string} path
 * @param {string} name
 * @param {string} args
 * @returns {$CancellablePromise<void>}
 */
export function AddCustomSoftware(path, name, args) {
    return $Call.ByID(430848108, path, name, args);
}

/**
 * AddExternalPath adds an external library path with auto-generated basename name, triggers rescan+reindex.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function AddExternalPath(path) {
    return $Call.ByID(3204589026, path);
}

/**
 * AddRecentModel pushes a libraryRef to the top of the recent models list.
 * If already present, it is moved to the top. List is capped at maxRecentModels.
 * @param {string} libraryRef
 * @returns {$CancellablePromise<void>}
 */
export function AddRecentModel(libraryRef) {
    return $Call.ByID(519246254, libraryRef);
}

/**
 * AddTag adds a tag to a model identified by its libraryRef.
 * @param {string} libraryRef
 * @param {string} tag
 * @returns {$CancellablePromise<void>}
 */
export function AddTag(libraryRef, tag) {
    return $Call.ByID(210682570, libraryRef, tag);
}

/**
 * AutoDetectMMD searches for MMD in common install paths and saves the result.
 * Returns the detected path, or an error if not found.
 * @returns {$CancellablePromise<string>}
 */
export function AutoDetectMMD() {
    return $Call.ByID(2288723387);
}

/**
 * BundleScene packages a scene JSON + all referenced asset files into a zip.
 * sceneJSON: the rewritten SceneFile JSON (libraryRef pointing to assets/ inside the bundle).
 * assetPaths: deduplicated absolute paths of files to include.
 * Each asset is stored at "assets/<relativeFromRoot>" preserving directory structure.
 * @param {string} targetPath
 * @param {string} sceneJSON
 * @param {string[]} assetPaths
 * @returns {$CancellablePromise<void>}
 */
export function BundleScene(targetPath, sceneJSON, assetPaths) {
    return $Call.ByID(1435810925, targetPath, sceneJSON, assetPaths);
}

/**
 * CheckForUpdate queries the GitHub latest release and reports whether a newer
 * version is available. Network/parse failures are reported via Error (and the
 * returned result is non-nil) so callers never need to branch on a hard error.
 * @returns {$CancellablePromise<$models.UpdateCheckResult | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2829612333).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CleanOrphanCache cleans extraction cache whose source zip no longer exists.
 * @returns {$CancellablePromise<number>}
 */
export function CleanOrphanCache() {
    return $Call.ByID(2413791992);
}

/**
 * ClearAllCaches removes ALL cache directories (extracted, thumbnails, serve)
 * in one shot. This is the unified entry point for the "clear all caches" UI action.
 * @returns {$CancellablePromise<void>}
 */
export function ClearAllCaches() {
    return $Call.ByID(2248552404);
}

/**
 * ClearExtractCache removes ALL extraction cache directories, forcing
 * re-extraction on the next model load (with current encoding fixes).
 * @returns {$CancellablePromise<void>}
 */
export function ClearExtractCache() {
    return $Call.ByID(4288953753);
}

/**
 * ClearThumbnailCache removes ALL thumbnail cache files, forcing
 * re-generation on the next model load.
 * @returns {$CancellablePromise<void>}
 */
export function ClearThumbnailCache() {
    return $Call.ByID(2575973390);
}

/**
 * DeleteDanceSet deletes a dance set by id.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDanceSet(id) {
    return $Call.ByID(2514613065, id);
}

/**
 * DeleteEnvPreset removes a .env file by name.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEnvPreset(name) {
    return $Call.ByID(4086876468, name);
}

/**
 * DeleteModelPreset removes a named model preset from the library.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteModelPreset(name) {
    return $Call.ByID(2236524258, name);
}

/**
 * DeletePresetScene deletes a named preset scene file.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeletePresetScene(name) {
    return $Call.ByID(2990819481, name);
}

/**
 * DeleteRenderPreset removes a named render preset.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRenderPreset(name) {
    return $Call.ByID(3324842907, name);
}

/**
 * ExtractZip extracts a zip file to the cache directory and returns the path
 * to the extracted PMX file specified by innerPath.
 * 
 * Cache hit: if the source zip's mtime and size haven't changed since last
 * extraction, returns the cached path immediately (Cached=true).
 * 
 * Cache miss: removes the old cache directory, re-extracts the entire zip,
 * writes a manifest.json, and returns the extracted path (Cached=false).
 * 
 * Zip slip protection: validates that every extracted entry stays within the
 * destination directory.
 * @param {string} zipPath
 * @param {string} innerPath
 * @returns {$CancellablePromise<$models.ExtractResult | null>}
 */
export function ExtractZip(zipPath, innerPath) {
    return $Call.ByID(1743254715, zipPath, innerPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetAllTags returns a deduplicated list of all tags across all models.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAllTags() {
    return $Call.ByID(3671882673).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetAppVersion returns the application version (injected via -ldflags at build time).
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(3698795868);
}

/**
 * GetBuildInfo returns build-time diagnostics (version + build time + commit + Go version).
 * @returns {$CancellablePromise<$models.BuildInfo | null>}
 */
export function GetBuildInfo() {
    return $Call.ByID(1666856379).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetCacheStats returns the total size and file count of all cache directories.
 * @returns {$CancellablePromise<$models.CacheStats | null>}
 */
export function GetCacheStats() {
    return $Call.ByID(2256096336).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetConfig reads the persisted config from disk with a read lock,
 * ensuring safe concurrent access with write operations.
 * @returns {$CancellablePromise<$models.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(445048723).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetDanceSets returns all dance sets.
 * @returns {$CancellablePromise<$models.DanceSet[]>}
 */
export function GetDanceSets() {
    return $Call.ByID(3501710593).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetDownloadAutoImport returns the current auto-import preference from config.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetDownloadAutoImport() {
    return $Call.ByID(1682181459);
}

/**
 * GetDownloadWatchStatus returns the current watch state (directory being watched or empty string).
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadWatchStatus() {
    return $Call.ByID(593372546);
}

/**
 * GetFavorites returns the current favorites list.
 * Reads from the built-in tag "收藏" in the tag system.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetFavorites() {
    return $Call.ByID(781046870).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetLibraryIndex reads the last scanned index from disk.
 * @returns {$CancellablePromise<$models.ModelEntry[]>}
 */
export function GetLibraryIndex() {
    return $Call.ByID(503588120).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetModelMeta parses the PMX header for a single PMX file and returns its metadata.
 * Returns empty meta on error (non-fatal), logs real errors.
 * @param {string} pmxPath
 * @returns {$CancellablePromise<$models.ModelMeta>}
 */
export function GetModelMeta(pmxPath) {
    return $Call.ByID(4247543483, pmxPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetModelMetaBatch parses PMX headers for multiple PMX files at once.
 * Returns a map keyed by pmxPath, with empty meta for unparseable files.
 * @param {string[]} paths
 * @returns {$CancellablePromise<{ [_ in string]?: $models.ModelMeta }>}
 */
export function GetModelMetaBatch(paths) {
    return $Call.ByID(1848295501, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetModelPresets lists all .mcupreset.json files in the model presets directory.
 * @returns {$CancellablePromise<$models.ModelPresetEntry[]>}
 */
export function GetModelPresets() {
    return $Call.ByID(1521700402).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetModelsByTag returns all libraryRefs that have a specific tag.
 * @param {string} tag
 * @returns {$CancellablePromise<string[]>}
 */
export function GetModelsByTag(tag) {
    return $Call.ByID(1267757778, tag).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetPath returns the effective path for a category.
 * @param {$models.Config | null} cfg
 * @param {string} category
 * @returns {$CancellablePromise<string>}
 */
export function GetPath(cfg, category) {
    return $Call.ByID(1008988522, cfg, category);
}

/**
 * GetPresetScenes lists numbered .mmascene files in the scene presets directory.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPresetScenes() {
    return $Call.ByID(2098641667).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetPresetScenesDir returns the absolute path of the scene presets directory.
 * @returns {$CancellablePromise<string>}
 */
export function GetPresetScenesDir() {
    return $Call.ByID(975665282);
}

/**
 * GetRecentModels returns the recently opened model libraryRefs (newest first).
 * @returns {$CancellablePromise<string[]>}
 */
export function GetRecentModels() {
    return $Call.ByID(814199676).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetRenderPresets returns all user-defined render presets.
 * @returns {$CancellablePromise<$models.RenderPreset[]>}
 */
export function GetRenderPresets() {
    return $Call.ByID(2867608539).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetTagsByModel returns the tags for a specific model.
 * @param {string} libraryRef
 * @returns {$CancellablePromise<string[]>}
 */
export function GetTagsByModel(libraryRef) {
    return $Call.ByID(3015085774, libraryRef).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetThumbnail returns a base64-encoded PNG thumbnail for the given model path.
 * @param {string} modelPath
 * @returns {$CancellablePromise<string>}
 */
export function GetThumbnail(modelPath) {
    return $Call.ByID(2513463283, modelPath);
}

/**
 * GetThumbnailBatch returns thumbnails for multiple model paths at once.
 * @param {string[]} paths
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetThumbnailBatch(paths) {
    return $Call.ByID(3092149765, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * ImportDanceSet creates a dance set from a VMD file and audio file.
 * Returns the generated dance set id.
 * @param {string} vmdPath
 * @param {string} audioPath
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ImportDanceSet(vmdPath, audioPath, name) {
    return $Call.ByID(3125599775, vmdPath, audioPath, name);
}

/**
 * ImportLocalFile imports a local file into the model library.
 * For .zip files, it finds the first .pmx inside and extracts via ImportZip.
 * For .pmx/.vmd files, it returns the path directly as an ExtractResult.
 * @param {string} path
 * @returns {$CancellablePromise<$models.ExtractResult | null>}
 */
export function ImportLocalFile(path) {
    return $Call.ByID(3787504267, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ImportZip opens a zip file, finds the first .pmx entry, and extracts via ExtractZip.
 * Returns *ExtractResult as a convenience for the frontend import flow.
 * @param {string} zipPath
 * @returns {$CancellablePromise<$models.ExtractResult | null>}
 */
export function ImportZip(zipPath) {
    return $Call.ByID(2890750837, zipPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsolateModelDir ensures the model file is served from a safe directory.
 * [doc:architecture] IsolateModelDir — 安全隔离：信任目录返回原目录，外部文件复制到 temp
 * 规范文档: docs/architecture.md §数据通道（HTTP 文件服务）
 * For files inside trusted roots, returns the original directory unchanged.
 * For external files, copies PMX + all siblings to a temp directory.
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function IsolateModelDir(filePath) {
    return $Call.ByID(2863350796, filePath);
}

/**
 * LaunchSoftware starts an executable by path with optional command-line arguments.
 * The args string is split into arguments and passed to the executable.
 * @param {string} path
 * @param {string} args
 * @returns {$CancellablePromise<void>}
 */
export function LaunchSoftware(path, args) {
    return $Call.ByID(3914501949, path, args);
}

/**
 * ListEnvPresets returns all user-saved env presets in the presets directory.
 * @returns {$CancellablePromise<$models.EnvPresetEntry[]>}
 */
export function ListEnvPresets() {
    return $Call.ByID(3980938190).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * ListSubDirs returns first-level subdirectory names under the given directory.
 * @param {string} dirPath
 * @returns {$CancellablePromise<string[]>}
 */
export function ListSubDirs(dirPath) {
    return $Call.ByID(568797923, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * LoadEnvPreset reads a .env JSON file by name.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function LoadEnvPreset(name) {
    return $Call.ByID(798602681, name);
}

/**
 * LoadLastScene reads the auto-saved scene state.
 * @returns {$CancellablePromise<string>}
 */
export function LoadLastScene() {
    return $Call.ByID(1176282909);
}

/**
 * LoadModelPreset reads a JSON model preset file from the given path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function LoadModelPreset(path) {
    return $Call.ByID(2705060931, path);
}

/**
 * LoadModelPresetFromLib reads a model preset JSON from the library by name.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function LoadModelPresetFromLib(name) {
    return $Call.ByID(4230958598, name);
}

/**
 * LoadOutfitFile reads <modelDir>/outfits.json. Returns empty string if not found.
 * @param {string} pmxPath
 * @returns {$CancellablePromise<string>}
 */
export function LoadOutfitFile(pmxPath) {
    return $Call.ByID(1729295606, pmxPath);
}

/**
 * LoadSceneFile reads a JSON scene file from the given path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function LoadSceneFile(path) {
    return $Call.ByID(1480065691, path);
}

/**
 * OpenInBlender launches Blender and opens the specified model file.
 * @param {string} modelPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenInBlender(modelPath) {
    return $Call.ByID(714380512, modelPath);
}

/**
 * OpenInMMD launches MikuMikuDance and opens the specified model file.
 * @param {string} modelPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenInMMD(modelPath) {
    return $Call.ByID(1122153542, modelPath);
}

/**
 * OpenSoftwareDir opens the software directory in the system file manager.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSoftwareDir() {
    return $Call.ByID(4046736841);
}

/**
 * OpenWithSoftware opens a model file with the specified software, replacing {model}
 * in the args template with the model path.
 * Each {model} token is replaced individually so paths with spaces stay as a single argv.
 * @param {string} modelPath
 * @param {string} softwarePath
 * @param {string} args
 * @returns {$CancellablePromise<void>}
 */
export function OpenWithSoftware(modelPath, softwarePath, args) {
    return $Call.ByID(3025395162, modelPath, softwarePath, args);
}

/**
 * RemoveCustomSoftware removes a user-defined software entry from the config by path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveCustomSoftware(path) {
    return $Call.ByID(3370268317, path);
}

/**
 * RemoveExternalPath removes an external library by path, triggers rescan+reindex.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveExternalPath(path) {
    return $Call.ByID(1961467951, path);
}

/**
 * RemoveTag removes a tag from a model.
 * @param {string} libraryRef
 * @param {string} tag
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTag(libraryRef, tag) {
    return $Call.ByID(2094550809, libraryRef, tag);
}

/**
 * RenameExternalPath renames an external library display name.
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameExternalPath(path, name) {
    return $Call.ByID(404682193, path, name);
}

/**
 * RenameModelPreset renames a model preset in the library.
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameModelPreset(oldName, newName) {
    return $Call.ByID(268780553, oldName, newName);
}

/**
 * SaveDanceSet saves or updates a dance set with the given id.
 * @param {string} id
 * @param {$models.DanceSet} ds
 * @returns {$CancellablePromise<void>}
 */
export function SaveDanceSet(id, ds) {
    return $Call.ByID(1409373315, id, ds);
}

/**
 * SaveEnvPreset writes a .env JSON file under env-presets/<name>.env.
 * The name is sanitized; the JSON content is the caller's responsibility.
 * @param {string} name
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveEnvPreset(name, jsonStr) {
    return $Call.ByID(1971888366, name, jsonStr);
}

/**
 * SaveLastScene stores the current scene state for auto-recovery on next launch.
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveLastScene(jsonStr) {
    return $Call.ByID(764740646, jsonStr);
}

/**
 * SaveModelPreset writes a JSON model preset file to the given path.
 * @param {string} jsonStr
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveModelPreset(jsonStr, path) {
    return $Call.ByID(891069976, jsonStr, path);
}

/**
 * SaveModelPresetToLib saves a model preset JSON to the library with the given name.
 * @param {string} name
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SaveModelPresetToLib(name, jsonStr) {
    return $Call.ByID(3034880824, name, jsonStr);
}

/**
 * SaveRenderPreset saves or updates a named render preset.
 * params is a JSON string of the RenderState fields.
 * @param {string} name
 * @param {string} params
 * @returns {$CancellablePromise<void>}
 */
export function SaveRenderPreset(name, params) {
    return $Call.ByID(2992881957, name, params);
}

/**
 * SaveSceneFile writes a JSON scene file to the given path.
 * @param {string} jsonStr
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveSceneFile(jsonStr, path) {
    return $Call.ByID(4126202692, jsonStr, path);
}

/**
 * SaveScenePreset saves a scene JSON as an auto-numbered .mmascene in the presets directory.
 * Returns the generated filename (e.g. "003.mmascene").
 * @param {string} jsonStr
 * @returns {$CancellablePromise<string>}
 */
export function SaveScenePreset(jsonStr) {
    return $Call.ByID(4250694969, jsonStr);
}

/**
 * SaveScreenshot saves a base64-encoded PNG screenshot to the specified directory.
 * @param {string} dir
 * @param {string} filename
 * @param {string} base64PNG
 * @returns {$CancellablePromise<void>}
 */
export function SaveScreenshot(dir, filename, base64PNG) {
    return $Call.ByID(1977239110, dir, filename, base64PNG);
}

/**
 * SaveThumbnail saves a base64-encoded PNG thumbnail for the given model path.
 * @param {string} modelPath
 * @param {string} base64PNG
 * @returns {$CancellablePromise<void>}
 */
export function SaveThumbnail(modelPath, base64PNG) {
    return $Call.ByID(2467575290, modelPath, base64PNG);
}

/**
 * ScanModelDir scans all resource directories and returns merged ModelEntry list.
 * Uses ResourceRoot + OverridePaths from config; scans each category directory
 * with extension filtering (no auto-classification by directory name).
 * @param {string} root
 * @param {$models.ExternalPath[]} external
 * @returns {$CancellablePromise<$models.ModelEntry[]>}
 */
export function ScanModelDir(root, external) {
    return $Call.ByID(586056714, root, external).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ScanSoftwareDir scans the software/ directory for .exe files, merges with user-added
 * custom software from config, and returns the combined list (deduplicated by path).
 * On Android, only returns config-persisted entries (no .exe scanning).
 * @returns {$CancellablePromise<$models.SoftwareEntry[]>}
 */
export function ScanSoftwareDir() {
    return $Call.ByID(1513075534).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * SelectAudioFile opens a file dialog to select an audio file
 * @returns {$CancellablePromise<string>}
 */
export function SelectAudioFile() {
    return $Call.ByID(212536397);
}

/**
 * SelectBundleSaveFile opens a save dialog for scene bundle files.
 * @returns {$CancellablePromise<string>}
 */
export function SelectBundleSaveFile() {
    return $Call.ByID(3840579068);
}

/**
 * SelectDir opens a directory picker dialog.
 * On Android, uses Wails v3 SAF-based file picker (GOOS=android).
 * @returns {$CancellablePromise<string>}
 */
export function SelectDir() {
    return $Call.ByID(1910889222);
}

/**
 * SelectEnvTextureFile opens a file dialog to select an environment/skybox texture.
 * @returns {$CancellablePromise<string>}
 */
export function SelectEnvTextureFile() {
    return $Call.ByID(3406785627);
}

/**
 * SelectExeFile opens a file dialog to select an executable file.
 * @returns {$CancellablePromise<string>}
 */
export function SelectExeFile() {
    return $Call.ByID(2290473707);
}

/**
 * SelectImportFile opens a file dialog to select PMX / ZIP / VMD files.
 * Used by the "导入文件" menu entry in library-core.ts.
 * @returns {$CancellablePromise<string>}
 */
export function SelectImportFile() {
    return $Call.ByID(750228192);
}

/**
 * SelectPMXFile opens a file dialog to select a PMX file
 * @returns {$CancellablePromise<string>}
 */
export function SelectPMXFile() {
    return $Call.ByID(3691658598);
}

/**
 * SelectPresetOpenFile opens a file dialog to pick a model preset file.
 * @returns {$CancellablePromise<string>}
 */
export function SelectPresetOpenFile() {
    return $Call.ByID(2752698286);
}

/**
 * SelectPresetSaveFile opens a save dialog for model preset files.
 * @returns {$CancellablePromise<string>}
 */
export function SelectPresetSaveFile() {
    return $Call.ByID(986190763);
}

/**
 * SelectSceneOpenFile opens a file dialog to pick a scene file.
 * @returns {$CancellablePromise<string>}
 */
export function SelectSceneOpenFile() {
    return $Call.ByID(741492271);
}

/**
 * SelectSceneSaveFile opens a save dialog for scene files.
 * @returns {$CancellablePromise<string>}
 */
export function SelectSceneSaveFile() {
    return $Call.ByID(2590952318);
}

/**
 * SelectVMDMotion opens a file dialog to select a VMD motion file
 * @returns {$CancellablePromise<string>}
 */
export function SelectVMDMotion() {
    return $Call.ByID(630359552);
}

/**
 * SelectVPDPose opens a file dialog to select a VPD pose file
 * @returns {$CancellablePromise<string>}
 */
export function SelectVPDPose() {
    return $Call.ByID(109862358);
}

/**
 * SetBlenderPath saves the Blender executable path to config.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetBlenderPath(path) {
    return $Call.ByID(1378814336, path);
}

/**
 * SetDisplayNamePriority persists the display name priority setting.
 * @param {string} priority
 * @returns {$CancellablePromise<void>}
 */
export function SetDisplayNamePriority(priority) {
    return $Call.ByID(502213362, priority);
}

/**
 * SetDownloadAutoImport persists the auto-import preference to config.
 * @param {boolean} auto
 * @returns {$CancellablePromise<void>}
 */
export function SetDownloadAutoImport(auto) {
    return $Call.ByID(2797996775, auto);
}

/**
 * SetDownloadWatchDir persists the download watch directory to config
 * and restarts the watcher (if dir is non-empty) or stops it (if dir is empty).
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetDownloadWatchDir(dir) {
    return $Call.ByID(2350742307, dir);
}

/**
 * SetEnvState persists the environment state (sky, ground, particles, fog, etc.).
 * @param {$models.EnvState} env
 * @returns {$CancellablePromise<void>}
 */
export function SetEnvState(env) {
    return $Call.ByID(4283504689, env);
}

/**
 * SetMMDPath saves the MMD executable path to config.
 * If path is empty, automatically detects MMD from common install locations.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetMMDPath(path) {
    return $Call.ByID(1687499778, path);
}

/**
 * SetOverridePath sets an override path for a category and triggers a rescan.
 * @param {string} category
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetOverridePath(category, path) {
    return $Call.ByID(4226099462, category, path);
}

/**
 * SetPerformanceMode persists the performance mode setting.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetPerformanceMode(mode) {
    return $Call.ByID(1916922602, mode);
}

/**
 * SetResourceRoot persists the resource root path, initialises all category
 * override paths to their default subdirectories, and triggers a rescan+reindex.
 * @param {string} root
 * @returns {$CancellablePromise<void>}
 */
export function SetResourceRoot(root) {
    return $Call.ByID(4185962653, root);
}

/**
 * SetUIAccent persists the accent color hex.
 * @param {string} hex
 * @returns {$CancellablePromise<void>}
 */
export function SetUIAccent(hex) {
    return $Call.ByID(1250434201, hex);
}

/**
 * SetUIAnimations enables or disables menu slide animations.
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetUIAnimations(on) {
    return $Call.ByID(213289368, on);
}

/**
 * SetUIBlurBg enables or disables background blur on overlays.
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetUIBlurBg(on) {
    return $Call.ByID(499239929, on);
}

/**
 * SetUIFontFamily persists the font family key ("system"|"noto"|"yahei").
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetUIFontFamily(key) {
    return $Call.ByID(3650360862, key);
}

/**
 * SetUIPopupWidth persists the popup width.
 * @param {number} width
 * @returns {$CancellablePromise<void>}
 */
export function SetUIPopupWidth(width) {
    return $Call.ByID(3186335453, width);
}

/**
 * SetUIScale persists the UI scale factor.
 * @param {number} scale
 * @returns {$CancellablePromise<void>}
 */
export function SetUIScale(scale) {
    return $Call.ByID(319781627, scale);
}

/**
 * ServiceShutdown implements application.ServiceShutdown interface.
 * @param {application$0.App | null} wailsApp
 * @returns {$CancellablePromise<void>}
 */
export function SetWailsApp(wailsApp) {
    return $Call.ByID(1808984472, wailsApp);
}

/**
 * StartFileServer starts (or reuses) an HTTP file server for dirPath,
 * serving files with basename fallback for texture lookup.
 * Multiple directories each get their own port; servers are never killed
 * until the app shuts down.
 * @param {string} dirPath
 * @returns {$CancellablePromise<number>}
 */
export function StartFileServer(dirPath) {
    return $Call.ByID(1163337096, dirPath);
}

/**
 * StartWatchDir starts fsnotify-based watching on the specified directory.
 * If already watching a directory, it stops the previous watcher first.
 * Only files with .zip/.pmx/.vmd extensions trigger notifications,
 * filtered through Magic Number detection to skip incomplete downloads.
 * On Android, file system watching is not supported — returns an error.
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function StartWatchDir(dir) {
    return $Call.ByID(1501929991, dir);
}

/**
 * StopFileServer shuts down the HTTP file server for the given directory.
 * Maintained for future cleanup use (e.g., scene teardown, directory unmount).
 * Currently unused by the frontend — HTTP servers run until app exit.
 * @param {string} dirPath
 * @returns {$CancellablePromise<void>}
 */
export function StopFileServer(dirPath) {
    return $Call.ByID(1672597494, dirPath);
}

/**
 * StopWatchDir stops the current directory watcher.
 * @returns {$CancellablePromise<void>}
 */
export function StopWatchDir() {
    return $Call.ByID(728590061);
}

/**
 * ToggleFavorite adds or removes a libraryRef from the favorites list.
 * Favorites are stored as the built-in tag "收藏" in the tag system.
 * @param {string} libraryRef
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFavorite(libraryRef) {
    return $Call.ByID(1527387235, libraryRef);
}

/**
 * UpdateCustomSoftware updates name and args for an existing custom software entry.
 * @param {string} path
 * @param {string} name
 * @param {string} args
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCustomSoftware(path, name, args) {
    return $Call.ByID(1840334952, path, name, args);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ExtractResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $models.BuildInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.CacheStats.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.Config.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.DanceSet.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.ModelEntry.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.ModelMeta.createFrom;
const $$createType16 = $Create.Map($Create.Any, $$createType15);
const $$createType17 = $models.ModelPresetEntry.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.RenderPreset.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Map($Create.Any, $Create.Any);
const $$createType22 = $models.EnvPresetEntry.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $models.SoftwareEntry.createFrom;
const $$createType25 = $Create.Array($$createType24);
