// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCustomSoftware adds a user-defined software entry to the config.
 */
export function AddCustomSoftware(path: string, name: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(430848108, path, name, args);
}

/**
 * AddExternalPath adds an external library path with auto-generated basename name, triggers rescan+reindex.
 */
export function AddExternalPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3204589026, path);
}

/**
 * AddRecentModel pushes a libraryRef to the top of the recent models list.
 * If already present, it is moved to the top. List is capped at maxRecentModels.
 */
export function AddRecentModel(libraryRef: string): $CancellablePromise<void> {
    return $Call.ByID(519246254, libraryRef);
}

/**
 * AddTag adds a tag to a model identified by its libraryRef.
 */
export function AddTag(libraryRef: string, tag: string): $CancellablePromise<void> {
    return $Call.ByID(210682570, libraryRef, tag);
}

/**
 * AutoDetectMMD searches for MMD in common install paths and saves the result.
 * Returns the detected path, or an error if not found.
 */
export function AutoDetectMMD(): $CancellablePromise<string> {
    return $Call.ByID(2288723387);
}

/**
 * BundleScene packages a scene JSON + all referenced asset files into a zip.
 * sceneJSON: the rewritten SceneFile JSON (libraryRef pointing to assets/ inside the bundle).
 * assetPaths: deduplicated absolute paths of files to include.
 * Each asset is stored at "assets/<relativeFromRoot>" preserving directory structure.
 */
export function BundleScene(targetPath: string, sceneJSON: string, assetPaths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1435810925, targetPath, sceneJSON, assetPaths);
}

/**
 * CheckForUpdate queries the GitHub latest release and reports whether a newer
 * version is available. Network/parse failures are reported via Error (and the
 * returned result is non-nil) so callers never need to branch on a hard error.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateCheckResult | null> {
    return $Call.ByID(2829612333);
}

/**
 * CleanOrphanCache cleans extraction cache whose source zip no longer exists.
 */
export function CleanOrphanCache(): $CancellablePromise<number> {
    return $Call.ByID(2413791992);
}

/**
 * ClearAllCaches removes ALL cache directories (extracted, thumbnails, serve)
 * in one shot. This is the unified entry point for the "clear all caches" UI action.
 */
export function ClearAllCaches(): $CancellablePromise<void> {
    return $Call.ByID(2248552404);
}

/**
 * ClearExtractCache removes ALL extraction cache directories, forcing
 * re-extraction on the next model load (with current encoding fixes).
 */
export function ClearExtractCache(): $CancellablePromise<void> {
    return $Call.ByID(4288953753);
}

/**
 * ClearThumbnailCache removes ALL thumbnail cache files, forcing
 * re-generation on the next model load.
 */
export function ClearThumbnailCache(): $CancellablePromise<void> {
    return $Call.ByID(2575973390);
}

/**
 * DeleteDanceSet deletes a dance set by id.
 */
export function DeleteDanceSet(id: string): $CancellablePromise<void> {
    return $Call.ByID(2514613065, id);
}

/**
 * DeleteEnvPreset removes a .env file by name.
 */
export function DeleteEnvPreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(4086876468, name);
}

/**
 * DeleteModelPreset removes a named model preset from the library.
 */
export function DeleteModelPreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(2236524258, name);
}

/**
 * DeletePresetScene deletes a named preset scene file.
 */
export function DeletePresetScene(name: string): $CancellablePromise<void> {
    return $Call.ByID(2990819481, name);
}

/**
 * DeleteRenderPreset removes a named render preset.
 */
export function DeleteRenderPreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(3324842907, name);
}

/**
 * ExtractZip extracts a zip file to the cache directory and returns the path
 * to the extracted PMX file specified by innerPath.
 * 
 * Cache hit: if the source zip's mtime and size haven't changed since last
 * extraction, returns the cached path immediately (Cached=true).
 * 
 * Cache miss: removes the old cache directory, re-extracts the entire zip,
 * writes a manifest.json, and returns the extracted path (Cached=false).
 * 
 * Zip slip protection: validates that every extracted entry stays within the
 * destination directory.
 */
export function ExtractZip(zipPath: string, innerPath: string): $CancellablePromise<$models.ExtractResult | null> {
    return $Call.ByID(1743254715, zipPath, innerPath);
}

/**
 * GetAllTags returns a deduplicated list of all tags across all models.
 */
export function GetAllTags(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3671882673);
}

/**
 * GetAppVersion returns the application version (injected via -ldflags at build time).
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(3698795868);
}

/**
 * GetBuildInfo returns build-time diagnostics (version + build time + commit + Go version).
 */
export function GetBuildInfo(): $CancellablePromise<$models.BuildInfo | null> {
    return $Call.ByID(1666856379);
}

/**
 * GetCacheStats returns the total size and file count of all cache directories.
 */
export function GetCacheStats(): $CancellablePromise<$models.CacheStats | null> {
    return $Call.ByID(2256096336);
}

/**
 * GetConfig reads the persisted config from disk with a read lock,
 * ensuring safe concurrent access with write operations.
 */
export function GetConfig(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(445048723);
}

/**
 * GetDanceSets returns all dance sets.
 */
export function GetDanceSets(): $CancellablePromise<$models.DanceSet[] | null> {
    return $Call.ByID(3501710593);
}

/**
 * GetDownloadAutoImport returns the current auto-import preference from config.
 */
export function GetDownloadAutoImport(): $CancellablePromise<boolean> {
    return $Call.ByID(1682181459);
}

/**
 * GetDownloadWatchStatus returns the current watch state (directory being watched or empty string).
 */
export function GetDownloadWatchStatus(): $CancellablePromise<string> {
    return $Call.ByID(593372546);
}

/**
 * GetLibraryIndex reads the last scanned index from disk.
 */
export function GetLibraryIndex(): $CancellablePromise<$models.ModelEntry[] | null> {
    return $Call.ByID(503588120);
}

/**
 * GetModelMeta parses the PMX header for a single PMX file and returns its metadata.
 * Returns empty meta on error (non-fatal), logs real errors.
 */
export function GetModelMeta(pmxPath: string): $CancellablePromise<$models.ModelMeta> {
    return $Call.ByID(4247543483, pmxPath);
}

/**
 * GetModelMetaBatch parses PMX headers for multiple PMX files at once.
 * Returns a map keyed by pmxPath, with empty meta for unparseable files.
 */
export function GetModelMetaBatch(paths: string[] | null): $CancellablePromise<{ [_ in string]?: $models.ModelMeta } | null> {
    return $Call.ByID(1848295501, paths);
}

/**
 * GetModelPresets lists all .mcupreset.json files in the model presets directory.
 */
export function GetModelPresets(): $CancellablePromise<$models.ModelPresetEntry[] | null> {
    return $Call.ByID(1521700402);
}

/**
 * GetModelsByTag returns all libraryRefs that have a specific tag.
 */
export function GetModelsByTag(tag: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1267757778, tag);
}

/**
 * GetPath returns the effective path for a category.
 */
export function GetPath(cfg: $models.Config | null, category: string): $CancellablePromise<string> {
    return $Call.ByID(1008988522, cfg, category);
}

/**
 * GetPresetScenes lists numbered .mmascene files in the scene presets directory.
 */
export function GetPresetScenes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2098641667);
}

/**
 * GetPresetScenesDir returns the absolute path of the scene presets directory.
 */
export function GetPresetScenesDir(): $CancellablePromise<string> {
    return $Call.ByID(975665282);
}

/**
 * GetRecentModels returns the recently opened model libraryRefs (newest first).
 */
export function GetRecentModels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(814199676);
}

/**
 * GetRenderPresets returns all user-defined render presets.
 */
export function GetRenderPresets(): $CancellablePromise<$models.RenderPreset[] | null> {
    return $Call.ByID(2867608539);
}

/**
 * GetTagsByModel returns the tags for a specific model.
 */
export function GetTagsByModel(libraryRef: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3015085774, libraryRef);
}

/**
 * GetThumbnail returns a base64-encoded PNG thumbnail for the given model path.
 */
export function GetThumbnail(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(2513463283, modelPath);
}

/**
 * GetThumbnailBatch returns thumbnails for multiple model paths at once.
 */
export function GetThumbnailBatch(paths: string[] | null): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(3092149765, paths);
}

/**
 * ImportDanceSet creates a dance set from a VMD file and audio file.
 * Returns the generated dance set id.
 */
export function ImportDanceSet(vmdPath: string, audioPath: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3125599775, vmdPath, audioPath, name);
}

/**
 * ImportLocalFile imports a local file into the model library.
 * For .zip files, it finds the first .pmx inside and extracts via ImportZip.
 * For .pmx/.vmd files, it returns the path directly as an ExtractResult.
 */
export function ImportLocalFile(path: string): $CancellablePromise<$models.ExtractResult | null> {
    return $Call.ByID(3787504267, path);
}

/**
 * ImportZip opens a zip file, finds the first .pmx entry, and extracts via ExtractZip.
 * Returns *ExtractResult as a convenience for the frontend import flow.
 */
export function ImportZip(zipPath: string): $CancellablePromise<$models.ExtractResult | null> {
    return $Call.ByID(2890750837, zipPath);
}

/**
 * IsolateModelDir ensures the model file is served from a safe directory.
 * [doc:architecture] IsolateModelDir — 安全隔离：信任目录返回原目录，外部文件复制到 temp
 * 规范文档: docs/architecture.md §数据通道（HTTP 文件服务）
 * For files inside trusted roots, returns the original directory unchanged.
 * For external files, copies PMX + all siblings to a temp directory.
 */
export function IsolateModelDir(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(2863350796, filePath);
}

/**
 * LaunchSoftware starts an executable by path with optional command-line arguments.
 * The args string is split into arguments and passed to the executable.
 */
export function LaunchSoftware(path: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(3914501949, path, args);
}

/**
 * ListEnvPresets returns all user-saved env presets in the presets directory.
 */
export function ListEnvPresets(): $CancellablePromise<$models.EnvPresetEntry[] | null> {
    return $Call.ByID(3980938190);
}

/**
 * ListSubDirs returns first-level subdirectory names under the given directory.
 */
export function ListSubDirs(dirPath: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(568797923, dirPath);
}

/**
 * LoadEnvPreset reads a .env JSON file by name.
 */
export function LoadEnvPreset(name: string): $CancellablePromise<string> {
    return $Call.ByID(798602681, name);
}

/**
 * LoadLastScene reads the auto-saved scene state.
 */
export function LoadLastScene(): $CancellablePromise<string> {
    return $Call.ByID(1176282909);
}

/**
 * LoadModelPreset reads a JSON model preset file from the given path.
 */
export function LoadModelPreset(path: string): $CancellablePromise<string> {
    return $Call.ByID(2705060931, path);
}

/**
 * LoadModelPresetFromLib reads a model preset JSON from the library by name.
 */
export function LoadModelPresetFromLib(name: string): $CancellablePromise<string> {
    return $Call.ByID(4230958598, name);
}

/**
 * LoadOutfitFile reads <modelDir>/outfits.json. Returns empty string if not found.
 */
export function LoadOutfitFile(pmxPath: string): $CancellablePromise<string> {
    return $Call.ByID(1729295606, pmxPath);
}

/**
 * LoadSceneFile reads a JSON scene file from the given path.
 */
export function LoadSceneFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1480065691, path);
}

/**
 * OpenInBlender launches Blender and opens the specified model file.
 */
export function OpenInBlender(modelPath: string): $CancellablePromise<void> {
    return $Call.ByID(714380512, modelPath);
}

/**
 * OpenInMMD launches MikuMikuDance and opens the specified model file.
 */
export function OpenInMMD(modelPath: string): $CancellablePromise<void> {
    return $Call.ByID(1122153542, modelPath);
}

/**
 * OpenSoftwareDir opens the software directory in the system file manager.
 */
export function OpenSoftwareDir(): $CancellablePromise<void> {
    return $Call.ByID(4046736841);
}

/**
 * OpenWithSoftware opens a model file with the specified software, replacing {model}
 * in the args template with the model path.
 * Each {model} token is replaced individually so paths with spaces stay as a single argv.
 */
export function OpenWithSoftware(modelPath: string, softwarePath: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(3025395162, modelPath, softwarePath, args);
}

/**
 * RemoveCustomSoftware removes a user-defined software entry from the config by path.
 */
export function RemoveCustomSoftware(path: string): $CancellablePromise<void> {
    return $Call.ByID(3370268317, path);
}

/**
 * RemoveExternalPath removes an external library by path, triggers rescan+reindex.
 */
export function RemoveExternalPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1961467951, path);
}

/**
 * RemoveTag removes a tag from a model.
 */
export function RemoveTag(libraryRef: string, tag: string): $CancellablePromise<void> {
    return $Call.ByID(2094550809, libraryRef, tag);
}

/**
 * RenameExternalPath renames an external library display name.
 */
export function RenameExternalPath(path: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(404682193, path, name);
}

/**
 * RenameModelPreset renames a model preset in the library.
 */
export function RenameModelPreset(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(268780553, oldName, newName);
}

/**
 * SaveDanceSet saves or updates a dance set with the given id.
 */
export function SaveDanceSet(id: string, ds: $models.DanceSet): $CancellablePromise<void> {
    return $Call.ByID(1409373315, id, ds);
}

/**
 * SaveEnvPreset writes a .env JSON file under env-presets/<name>.env.
 * The name is sanitized; the JSON content is the caller's responsibility.
 */
export function SaveEnvPreset(name: string, jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(1971888366, name, jsonStr);
}

/**
 * SaveLastScene stores the current scene state for auto-recovery on next launch.
 */
export function SaveLastScene(jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(764740646, jsonStr);
}

/**
 * SaveModelPreset writes a JSON model preset file to the given path.
 */
export function SaveModelPreset(jsonStr: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(891069976, jsonStr, path);
}

/**
 * SaveModelPresetToLib saves a model preset JSON to the library with the given name.
 */
export function SaveModelPresetToLib(name: string, jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(3034880824, name, jsonStr);
}

/**
 * SaveRenderPreset saves or updates a named render preset.
 * params is a JSON string of the RenderState fields.
 */
export function SaveRenderPreset(name: string, params: string): $CancellablePromise<void> {
    return $Call.ByID(2992881957, name, params);
}

/**
 * SaveSceneFile writes a JSON scene file to the given path.
 */
export function SaveSceneFile(jsonStr: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(4126202692, jsonStr, path);
}

/**
 * SaveScenePreset saves a scene JSON as an auto-numbered .mmascene in the presets directory.
 * Returns the generated filename (e.g. "003.mmascene").
 */
export function SaveScenePreset(jsonStr: string): $CancellablePromise<string> {
    return $Call.ByID(4250694969, jsonStr);
}

/**
 * SaveScreenshot saves a base64-encoded PNG screenshot to the specified directory.
 */
export function SaveScreenshot(dir: string, filename: string, base64PNG: string): $CancellablePromise<void> {
    return $Call.ByID(1977239110, dir, filename, base64PNG);
}

/**
 * SaveThumbnail saves a base64-encoded PNG thumbnail for the given model path.
 */
export function SaveThumbnail(modelPath: string, base64PNG: string): $CancellablePromise<void> {
    return $Call.ByID(2467575290, modelPath, base64PNG);
}

/**
 * ScanModelDir scans all resource directories and returns merged ModelEntry list.
 * Uses ResourceRoot + OverridePaths from config; scans each category directory
 * with extension filtering (no auto-classification by directory name).
 */
export function ScanModelDir(root: string, external: $models.ExternalPath[] | null): $CancellablePromise<$models.ModelEntry[] | null> {
    return $Call.ByID(586056714, root, external);
}

/**
 * ScanSoftwareDir scans the software/ directory for .exe files, merges with user-added
 * custom software from config, and returns the combined list (deduplicated by path).
 * On Android, only returns config-persisted entries (no .exe scanning).
 */
export function ScanSoftwareDir(): $CancellablePromise<$models.SoftwareEntry[] | null> {
    return $Call.ByID(1513075534);
}

/**
 * SelectAudioFile opens a file dialog to select an audio file
 */
export function SelectAudioFile(): $CancellablePromise<string> {
    return $Call.ByID(212536397);
}

/**
 * SelectBundleSaveFile opens a save dialog for scene bundle files.
 */
export function SelectBundleSaveFile(): $CancellablePromise<string> {
    return $Call.ByID(3840579068);
}

/**
 * SelectDir opens a directory picker dialog.
 * On Android, uses Wails v3 SAF-based file picker (GOOS=android).
 */
export function SelectDir(): $CancellablePromise<string> {
    return $Call.ByID(1910889222);
}

/**
 * SelectEnvTextureFile opens a file dialog to select an environment/skybox texture.
 */
export function SelectEnvTextureFile(): $CancellablePromise<string> {
    return $Call.ByID(3406785627);
}

/**
 * SelectExeFile opens a file dialog to select an executable file.
 */
export function SelectExeFile(): $CancellablePromise<string> {
    return $Call.ByID(2290473707);
}

/**
 * SelectImportFile opens a file dialog to select PMX / ZIP / VMD files.
 * Used by the "导入文件" menu entry in library-core.ts.
 */
export function SelectImportFile(): $CancellablePromise<string> {
    return $Call.ByID(750228192);
}

/**
 * SelectPMXFile opens a file dialog to select a PMX file
 */
export function SelectPMXFile(): $CancellablePromise<string> {
    return $Call.ByID(3691658598);
}

/**
 * SelectPresetOpenFile opens a file dialog to pick a model preset file.
 */
export function SelectPresetOpenFile(): $CancellablePromise<string> {
    return $Call.ByID(2752698286);
}

/**
 * SelectPresetSaveFile opens a save dialog for model preset files.
 */
export function SelectPresetSaveFile(): $CancellablePromise<string> {
    return $Call.ByID(986190763);
}

/**
 * SelectSceneOpenFile opens a file dialog to pick a scene file.
 */
export function SelectSceneOpenFile(): $CancellablePromise<string> {
    return $Call.ByID(741492271);
}

/**
 * SelectSceneSaveFile opens a save dialog for scene files.
 */
export function SelectSceneSaveFile(): $CancellablePromise<string> {
    return $Call.ByID(2590952318);
}

/**
 * SelectVMDMotion opens a file dialog to select a VMD motion file
 */
export function SelectVMDMotion(): $CancellablePromise<string> {
    return $Call.ByID(630359552);
}

/**
 * SelectVPDPose opens a file dialog to select a VPD pose file
 */
export function SelectVPDPose(): $CancellablePromise<string> {
    return $Call.ByID(109862358);
}

/**
 * SetBlenderPath saves the Blender executable path to config.
 */
export function SetBlenderPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1378814336, path);
}

/**
 * SetDisplayNamePriority persists the display name priority setting.
 */
export function SetDisplayNamePriority(priority: string): $CancellablePromise<void> {
    return $Call.ByID(502213362, priority);
}

/**
 * SetDownloadAutoImport persists the auto-import preference to config.
 */
export function SetDownloadAutoImport(auto: boolean): $CancellablePromise<void> {
    return $Call.ByID(2797996775, auto);
}

/**
 * SetDownloadWatchDir persists the download watch directory to config
 * and restarts the watcher (if dir is non-empty) or stops it (if dir is empty).
 */
export function SetDownloadWatchDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2350742307, dir);
}

/**
 * SetEnvState persists the environment state (sky, ground, particles, fog, etc.).
 */
export function SetEnvState(env: $models.EnvState): $CancellablePromise<void> {
    return $Call.ByID(4283504689, env);
}

/**
 * SetMMDPath saves the MMD executable path to config.
 * If path is empty, automatically detects MMD from common install locations.
 */
export function SetMMDPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1687499778, path);
}

/**
 * SetOverridePath sets an override path for a category and triggers a rescan.
 */
export function SetOverridePath(category: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(4226099462, category, path);
}

/**
 * SetPerformanceMode persists the performance mode setting.
 */
export function SetPerformanceMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(1916922602, mode);
}

/**
 * SetResourceRoot persists the resource root path, initialises all category
 * override paths to their default subdirectories, and triggers a rescan+reindex.
 */
export function SetResourceRoot(root: string): $CancellablePromise<void> {
    return $Call.ByID(4185962653, root);
}

/**
 * SetUIAccent persists the accent color hex.
 */
export function SetUIAccent(hex: string): $CancellablePromise<void> {
    return $Call.ByID(1250434201, hex);
}

/**
 * SetUIAnimations enables or disables menu slide animations.
 */
export function SetUIAnimations(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(213289368, on);
}

/**
 * SetUIAutoUpdate persists whether to auto-check for updates on startup.
 */
export function SetUIAutoUpdate(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3428263833, on);
}

/**
 * SetUIBlurBg enables or disables background blur on overlays.
 */
export function SetUIBlurBg(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(499239929, on);
}

/**
 * SetUIFontFamily persists the font family key ("system"|"noto"|"yahei").
 */
export function SetUIFontFamily(key: string): $CancellablePromise<void> {
    return $Call.ByID(3650360862, key);
}

/**
 * SetUIPopupWidth persists the popup width.
 */
export function SetUIPopupWidth(width: number): $CancellablePromise<void> {
    return $Call.ByID(3186335453, width);
}

/**
 * SetUIScale persists the UI scale factor.
 */
export function SetUIScale(scale: number): $CancellablePromise<void> {
    return $Call.ByID(319781627, scale);
}

/**
 * SetUIState persists the full UI state (scale, popupWidth, rendering settings, etc.).
 * Follows the same full-replace pattern as SetEnvState.
 */
export function SetUIState(ui: $models.UIState): $CancellablePromise<void> {
    return $Call.ByID(1015886004, ui);
}

/**
 * ServiceShutdown implements application.ServiceShutdown interface.
 */
export function SetWailsApp(wailsApp: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1808984472, wailsApp);
}

/**
 * StartFileServer starts (or reuses) an HTTP file server for dirPath,
 * serving files with basename fallback for texture lookup.
 * Multiple directories each get their own port; servers are never killed
 * until the app shuts down.
 */
export function StartFileServer(dirPath: string): $CancellablePromise<number> {
    return $Call.ByID(1163337096, dirPath);
}

/**
 * StartWatchDir starts fsnotify-based watching on the specified directory.
 * If already watching a directory, it stops the previous watcher first.
 * Only files with .zip/.pmx/.vmd extensions trigger notifications,
 * filtered through Magic Number detection to skip incomplete downloads.
 * On Android, file system watching is not supported — returns an error.
 */
export function StartWatchDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1501929991, dir);
}

/**
 * StopWatchDir stops the current directory watcher.
 */
export function StopWatchDir(): $CancellablePromise<void> {
    return $Call.ByID(728590061);
}

/**
 * ToggleFavorite adds or removes a libraryRef from the favorites list.
 * Favorites are stored as the built-in tag "收藏" in the tag system.
 */
export function ToggleFavorite(libraryRef: string): $CancellablePromise<void> {
    return $Call.ByID(1527387235, libraryRef);
}

/**
 * UpdateCustomSoftware updates name and args for an existing custom software entry.
 */
export function UpdateCustomSoftware(path: string, name: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(1840334952, path, name, args);
}
