// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClothConfig stores XPBD cloth simulation parameters.
 */
export class ClothConfig {
    /**
     * Creates a new ClothConfig instance.
     * @param {Partial<ClothConfig>} [$$source = {}] - The source object to create the ClothConfig.
     */
    constructor($$source = {}) {
        if (!("anchorBone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["anchorBone"] = "";
        }
        if (!("topology" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["topology"] = "";
        }
        if (!("innerRadius" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["innerRadius"] = 0;
        }
        if (!("length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["length"] = 0;
        }
        if (!("slope" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["slope"] = 0;
        }
        if (!("segmentsH" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["segmentsH"] = 0;
        }
        if (!("segmentsV" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["segmentsV"] = 0;
        }
        if (!("particleRadius" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["particleRadius"] = 0;
        }
        if (!("compliance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compliance"] = 0;
        }
        if (!("totalMass" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalMass"] = 0;
        }
        if (!("damping" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["damping"] = 0;
        }
        if (!("gravityScale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gravityScale"] = 0;
        }
        if (!("bendCompliance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bendCompliance"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClothConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClothConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClothConfig(/** @type {Partial<ClothConfig>} */($$parsedSource));
    }
}

/**
 * Config holds persistent user settings.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("ui_state" in $$source)) {
            /**
             * @member
             * @type {UIState}
             */
            this["ui_state"] = (new UIState());
        }
        if (/** @type {any} */(false)) {
            /**
             * 迁移后清空，保留字段用于自动迁移
             * @member
             * @type {string | undefined}
             */
            this["library_root"] = undefined;
        }
        if (!("resource_root" in $$source)) {
            /**
             * 总根目录
             * @member
             * @type {string}
             */
            this["resource_root"] = "";
        }
        if (!("override_paths" in $$source)) {
            /**
             * 各类型路径覆写
             * @member
             * @type {OverridePaths}
             */
            this["override_paths"] = (new OverridePaths());
        }
        if (!("external_paths" in $$source)) {
            /**
             * @member
             * @type {ExternalPath[]}
             */
            this["external_paths"] = [];
        }
        if (!("blender_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["blender_path"] = "";
        }
        if (!("display_name_priority" in $$source)) {
            /**
             * "name_jp" | "name_en" | "filename"
             * @member
             * @type {string}
             */
            this["display_name_priority"] = "";
        }
        if (!("download_watch_dir" in $$source)) {
            /**
             * 监听目录，空则不监听
             * @member
             * @type {string}
             */
            this["download_watch_dir"] = "";
        }
        if (!("download_auto_import" in $$source)) {
            /**
             * true 则跳过确认直接导入
             * @member
             * @type {boolean}
             */
            this["download_auto_import"] = false;
        }
        if (!("favorites" in $$source)) {
            /**
             * libraryRef 数组，收藏的模型
             * @member
             * @type {string[]}
             */
            this["favorites"] = [];
        }
        if (!("render_presets" in $$source)) {
            /**
             * 用户保存的渲染预设
             * @member
             * @type {RenderPreset[]}
             */
            this["render_presets"] = [];
        }
        if (!("mmd_path" in $$source)) {
            /**
             * MikuMikuDance 可执行文件路径，空则自动检测
             * @member
             * @type {string}
             */
            this["mmd_path"] = "";
        }
        if (!("custom_software" in $$source)) {
            /**
             * 用户手动添加的软件（Managed=true）
             * @member
             * @type {SoftwareEntry[]}
             */
            this["custom_software"] = [];
        }
        if (!("tags" in $$source)) {
            /**
             * libraryRef → []tag 列表
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["tags"] = {};
        }
        if (!("dance_sets" in $$source)) {
            /**
             * 舞蹈套装，key = 套装 ID
             * @member
             * @type {{ [_ in string]?: DanceSet }}
             */
            this["dance_sets"] = {};
        }
        if (!("recent_models" in $$source)) {
            /**
             * libraryRef 数组，最近打开的模型（最多20条）
             * @member
             * @type {string[]}
             */
            this["recent_models"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * 环境状态（天空/地面/粒子等），nil=使用前端默认
             * @member
             * @type {EnvState | null | undefined}
             */
            this["env"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        const $$createField9_0 = $$createType4;
        const $$createField10_0 = $$createType6;
        const $$createField12_0 = $$createType8;
        const $$createField13_0 = $$createType9;
        const $$createField14_0 = $$createType11;
        const $$createField15_0 = $$createType4;
        const $$createField16_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ui_state" in $$parsedSource) {
            $$parsedSource["ui_state"] = $$createField0_0($$parsedSource["ui_state"]);
        }
        if ("override_paths" in $$parsedSource) {
            $$parsedSource["override_paths"] = $$createField3_0($$parsedSource["override_paths"]);
        }
        if ("external_paths" in $$parsedSource) {
            $$parsedSource["external_paths"] = $$createField4_0($$parsedSource["external_paths"]);
        }
        if ("favorites" in $$parsedSource) {
            $$parsedSource["favorites"] = $$createField9_0($$parsedSource["favorites"]);
        }
        if ("render_presets" in $$parsedSource) {
            $$parsedSource["render_presets"] = $$createField10_0($$parsedSource["render_presets"]);
        }
        if ("custom_software" in $$parsedSource) {
            $$parsedSource["custom_software"] = $$createField12_0($$parsedSource["custom_software"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField13_0($$parsedSource["tags"]);
        }
        if ("dance_sets" in $$parsedSource) {
            $$parsedSource["dance_sets"] = $$createField14_0($$parsedSource["dance_sets"]);
        }
        if ("recent_models" in $$parsedSource) {
            $$parsedSource["recent_models"] = $$createField15_0($$parsedSource["recent_models"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField16_0($$parsedSource["env"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * DanceSet represents a dance set combining VMD motion, audio, and metadata.
 */
export class DanceSet {
    /**
     * Creates a new DanceSet instance.
     * @param {Partial<DanceSet>} [$$source = {}] - The source object to create the DanceSet.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 套装名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("vmd_path" in $$source)) {
            /**
             * VMD 文件路径
             * @member
             * @type {string}
             */
            this["vmd_path"] = "";
        }
        if (!("audio_path" in $$source)) {
            /**
             * 音频文件路径
             * @member
             * @type {string}
             */
            this["audio_path"] = "";
        }
        if (!("audio_offset" in $$source)) {
            /**
             * 音频偏移（秒）
             * @member
             * @type {number}
             */
            this["audio_offset"] = 0;
        }
        if (!("description" in $$source)) {
            /**
             * 描述（可选）
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("thumbnail" in $$source)) {
            /**
             * 缩略图 base64（可选）
             * @member
             * @type {string}
             */
            this["thumbnail"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * 来源库名
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DanceSet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DanceSet}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DanceSet(/** @type {Partial<DanceSet>} */($$parsedSource));
    }
}

/**
 * EnvPresetEntry is a catalog item returned by ListEnvPresets.
 */
export class EnvPresetEntry {
    /**
     * Creates a new EnvPresetEntry instance.
     * @param {Partial<EnvPresetEntry>} [$$source = {}] - The source object to create the EnvPresetEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvPresetEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvPresetEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvPresetEntry(/** @type {Partial<EnvPresetEntry>} */($$parsedSource));
    }
}

/**
 * EnvState stores the full environment configuration (sky, ground, particles, fog, etc.).
 */
export class EnvState {
    /**
     * Creates a new EnvState instance.
     * @param {Partial<EnvState>} [$$source = {}] - The source object to create the EnvState.
     */
    constructor($$source = {}) {
        if (!("skyMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skyMode"] = "";
        }
        if (!("skyColorTop" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["skyColorTop"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("skyColorMid" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["skyColorMid"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("skyColorBot" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["skyColorBot"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("skyTexture" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skyTexture"] = "";
        }
        if (!("skyRotationY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skyRotationY"] = 0;
        }
        if (!("skyRotationSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skyRotationSpeed"] = 0;
        }
        if (!("skyBrightness" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skyBrightness"] = 0;
        }
        if (!("starsEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["starsEnabled"] = false;
        }
        if (!("envIntensity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["envIntensity"] = 0;
        }
        if (!("groundVisible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["groundVisible"] = false;
        }
        if (!("groundMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groundMode"] = "";
        }
        if (!("groundColor" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["groundColor"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("groundAlpha" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["groundAlpha"] = 0;
        }
        if (!("windEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["windEnabled"] = false;
        }
        if (!("windDirection" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["windDirection"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("windSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windSpeed"] = 0;
        }
        if (!("particleEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["particleEnabled"] = false;
        }
        if (!("particleType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["particleType"] = "";
        }
        if (!("particleEmitRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["particleEmitRate"] = 0;
        }
        if (!("particleSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["particleSize"] = 0;
        }
        if (!("particleSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["particleSpeed"] = 0;
        }
        if (!("waterEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["waterEnabled"] = false;
        }
        if (!("waterLevel" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["waterLevel"] = 0;
        }
        if (!("waterColor" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["waterColor"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("waterTransparency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["waterTransparency"] = 0;
        }
        if (!("waterWaveHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["waterWaveHeight"] = 0;
        }
        if (!("waterSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["waterSize"] = 0;
        }
        if (!("waterAnimSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["waterAnimSpeed"] = 0;
        }
        if (!("fresnelBias" in $$source)) {
            /**
             * 水面高级着色器参数（持久化，避免材质重建时重置）
             * @member
             * @type {number}
             */
            this["fresnelBias"] = 0;
        }
        if (!("fresnelPower" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fresnelPower"] = 0;
        }
        if (!("diffuseStrength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diffuseStrength"] = 0;
        }
        if (!("ambientStrength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ambientStrength"] = 0;
        }
        if (!("foamTransitionRange" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["foamTransitionRange"] = 0;
        }
        if (!("rippleNormalStrength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rippleNormalStrength"] = 0;
        }
        if (!("rippleGlintStrength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rippleGlintStrength"] = 0;
        }
        if (!("causticColor1" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["causticColor1"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("causticColor2" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["causticColor2"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("causticScrollX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["causticScrollX"] = 0;
        }
        if (!("causticScrollY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["causticScrollY"] = 0;
        }
        if (!("fresnelAlphaInfluence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fresnelAlphaInfluence"] = 0;
        }
        if (!("foamAlphaInfluence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["foamAlphaInfluence"] = 0;
        }
        if (!("cloudsEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cloudsEnabled"] = false;
        }
        if (!("cloudCover" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cloudCover"] = 0;
        }
        if (!("cloudScale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cloudScale"] = 0;
        }
        if (!("cloudHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cloudHeight"] = 0;
        }
        if (!("fogEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fogEnabled"] = false;
        }
        if (!("fogColor" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["fogColor"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("fogDensity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fogDensity"] = 0;
        }
        if (!("clothEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clothEnabled"] = false;
        }
        if (!("clothConfig" in $$source)) {
            /**
             * @member
             * @type {ClothConfig}
             */
            this["clothConfig"] = (new ClothConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvState}
     */
    static createFrom($$source = {}) {
        const $$createField50_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clothConfig" in $$parsedSource) {
            $$parsedSource["clothConfig"] = $$createField50_0($$parsedSource["clothConfig"]);
        }
        return new EnvState(/** @type {Partial<EnvState>} */($$parsedSource));
    }
}

/**
 * ExternalPath represents an external library mount point.
 */
export class ExternalPath {
    /**
     * Creates a new ExternalPath instance.
     * @param {Partial<ExternalPath>} [$$source = {}] - The source object to create the ExternalPath.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * Absolute path to external library root
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * Display name (default basename, user-renameable)
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExternalPath instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExternalPath}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExternalPath(/** @type {Partial<ExternalPath>} */($$parsedSource));
    }
}

/**
 * ExtractResult holds the result of a zip extraction.
 */
export class ExtractResult {
    /**
     * Creates a new ExtractResult instance.
     * @param {Partial<ExtractResult>} [$$source = {}] - The source object to create the ExtractResult.
     */
    constructor($$source = {}) {
        if (!("file_path" in $$source)) {
            /**
             * Absolute path to extracted file (PMX or VMD)
             * @member
             * @type {string}
             */
            this["file_path"] = "";
        }
        if (!("dir" in $$source)) {
            /**
             * Extraction root directory (for HTTP server)
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("cached" in $$source)) {
            /**
             * Whether cache was hit (no re-extract)
             * @member
             * @type {boolean}
             */
            this["cached"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtractResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtractResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtractResult(/** @type {Partial<ExtractResult>} */($$parsedSource));
    }
}

/**
 * ModelEntry represents a model, motion, or zip entry found during library scan.
 */
export class ModelEntry {
    /**
     * Creates a new ModelEntry instance.
     * @param {Partial<ModelEntry>} [$$source = {}] - The source object to create the ModelEntry.
     */
    constructor($$source = {}) {
        if (!("dir" in $$source)) {
            /**
             * Model directory (absolute); for zip entries, the zip's directory
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("file_path" in $$source)) {
            /**
             * file absolute path (.pmx or .vmd; also called PMXPath for historical reasons); for zip entries, the zip path
             * @member
             * @type {string}
             */
            this["file_path"] = "";
        }
        if (!("name_jp" in $$source)) {
            /**
             * PMX header: local name
             * @member
             * @type {string}
             */
            this["name_jp"] = "";
        }
        if (!("name_en" in $$source)) {
            /**
             * PMX header: universal name; for VMD: basename
             * @member
             * @type {string}
             */
            this["name_en"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * PMX header: local comment (truncated)
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("has_thumb" in $$source)) {
            /**
             * Whether a thumbnail exists
             * @member
             * @type {boolean}
             */
            this["has_thumb"] = false;
        }
        if (!("type" in $$source)) {
            /**
             * "actor" | "motion" | "stage" | "dressing" | "bundle" | "effect" | "scene" | "other"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * "pmx" | "vmd" | "zip"
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("container" in $$source)) {
            /**
             * "file" | "zip"
             * @member
             * @type {string}
             */
            this["container"] = "";
        }
        if (!("zip_inner" in $$source)) {
            /**
             * Relative path inside zip (only for container=zip)
             * @member
             * @type {string}
             */
            this["zip_inner"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * DanceXR top-level category dir name (empty if none)
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * Source library name: empty for main lib, ExternalPath.Name for externals
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelEntry(/** @type {Partial<ModelEntry>} */($$parsedSource));
    }
}

/**
 * ModelMeta holds PMX header metadata for on-demand parsing.
 * Returned by GetModelMeta / GetModelMetaBatch.
 */
export class ModelMeta {
    /**
     * Creates a new ModelMeta instance.
     * @param {Partial<ModelMeta>} [$$source = {}] - The source object to create the ModelMeta.
     */
    constructor($$source = {}) {
        if (!("name_jp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name_jp"] = "";
        }
        if (!("name_en" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name_en"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * PMX header: local comment (truncated)
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelMeta(/** @type {Partial<ModelMeta>} */($$parsedSource));
    }
}

/**
 * ModelPresetEntry is a listing entry for a model preset in the library.
 */
export class ModelPresetEntry {
    /**
     * Creates a new ModelPresetEntry instance.
     * @param {Partial<ModelPresetEntry>} [$$source = {}] - The source object to create the ModelPresetEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("presetName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["presetName"] = "";
        }
        if (!("modelName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelName"] = "";
        }
        if (!("modelRef" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelRef"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("autoApply" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoApply"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelPresetEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelPresetEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelPresetEntry(/** @type {Partial<ModelPresetEntry>} */($$parsedSource));
    }
}

/**
 * OverridePaths allows per-category path overrides.
 * If a field is empty, the default path under ResourceRoot is used.
 */
export class OverridePaths {
    /**
     * Creates a new OverridePaths instance.
     * @param {Partial<OverridePaths>} [$$source = {}] - The source object to create the OverridePaths.
     */
    constructor($$source = {}) {
        if (!("pmx" in $$source)) {
            /**
             * 默认 resource_root/PMX
             * @member
             * @type {string}
             */
            this["pmx"] = "";
        }
        if (!("vmd" in $$source)) {
            /**
             * 默认 resource_root/VMD
             * @member
             * @type {string}
             */
            this["vmd"] = "";
        }
        if (!("stage" in $$source)) {
            /**
             * 默认 resource_root/stage
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("environment" in $$source)) {
            /**
             * 默认 resource_root/environment
             * @member
             * @type {string}
             */
            this["environment"] = "";
        }
        if (!("md_dress" in $$source)) {
            /**
             * 默认 resource_root/MD-dress
             * @member
             * @type {string}
             */
            this["md_dress"] = "";
        }
        if (!("setting" in $$source)) {
            /**
             * 默认 resource_root/setting
             * @member
             * @type {string}
             */
            this["setting"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverridePaths instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OverridePaths}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverridePaths(/** @type {Partial<OverridePaths>} */($$parsedSource));
    }
}

/**
 * RenderPreset stores a user-defined rendering preset.
 */
export class RenderPreset {
    /**
     * Creates a new RenderPreset instance.
     * @param {Partial<RenderPreset>} [$$source = {}] - The source object to create the RenderPreset.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("params" in $$source)) {
            /**
             * RenderState fields as flat key-value pairs
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["params"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RenderPreset}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField1_0($$parsedSource["params"]);
        }
        return new RenderPreset(/** @type {Partial<RenderPreset>} */($$parsedSource));
    }
}

/**
 * SoftwareEntry represents an executable found in the software/ directory or user-added.
 */
export class SoftwareEntry {
    /**
     * Creates a new SoftwareEntry instance.
     * @param {Partial<SoftwareEntry>} [$$source = {}] - The source object to create the SoftwareEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Display name (without extension)
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * Full absolute path
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * "blender" | "mmd" | "pmxeditor" | "other"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("args" in $$source)) {
            /**
             * Command-line template, supports {model} placeholder
             * @member
             * @type {string}
             */
            this["args"] = "";
        }
        if (!("managed" in $$source)) {
            /**
             * true=Config-persisted custom entry, false=scanned from software/
             * @member
             * @type {boolean}
             */
            this["managed"] = false;
        }
        if (!("icon" in $$source)) {
            /**
             * Reserved for future .exe icon extraction
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SoftwareEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SoftwareEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SoftwareEntry(/** @type {Partial<SoftwareEntry>} */($$parsedSource));
    }
}

/**
 * UIState stores user-customizable UI preferences.
 */
export class UIState {
    /**
     * Creates a new UIState instance.
     * @param {Partial<UIState>} [$$source = {}] - The source object to create the UIState.
     */
    constructor($$source = {}) {
        if (!("scale" in $$source)) {
            /**
             * 0.8~1.3, default 1.0
             * @member
             * @type {number}
             */
            this["scale"] = 0;
        }
        if (!("popupWidth" in $$source)) {
            /**
             * 220~380, default 280
             * @member
             * @type {number}
             */
            this["popupWidth"] = 0;
        }
        if (!("accent" in $$source)) {
            /**
             * hex, default "#4a6cf7"
             * @member
             * @type {string}
             */
            this["accent"] = "";
        }
        if (!("fontFamily" in $$source)) {
            /**
             * "system"|"noto"|"yahei"
             * @member
             * @type {string}
             */
            this["fontFamily"] = "";
        }
        if (!("animations" in $$source)) {
            /**
             * enable menu slide animations
             * @member
             * @type {boolean}
             */
            this["animations"] = false;
        }
        if (!("blurBg" in $$source)) {
            /**
             * enable background blur on overlays
             * @member
             * @type {boolean}
             */
            this["blurBg"] = false;
        }
        if (!("performanceMode" in $$source)) {
            /**
             * "auto"|"quality"|"balanced"|"performance"
             * @member
             * @type {string}
             */
            this["performanceMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UIState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIState(/** @type {Partial<UIState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = UIState.createFrom;
const $$createType1 = OverridePaths.createFrom;
const $$createType2 = ExternalPath.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = RenderPreset.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = SoftwareEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $$createType4);
const $$createType10 = DanceSet.createFrom;
const $$createType11 = $Create.Map($Create.Any, $$createType10);
const $$createType12 = EnvState.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = ClothConfig.createFrom;
const $$createType15 = $Create.Map($Create.Any, $Create.Any);
