// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuildInfo holds build-time diagnostics for the "About" page.
 */
export interface BuildInfo {
    "version": string;
    "buildTime": string;
    "commitHash": string;
    "goVersion": string;
}

/**
 * CacheStats holds size/file-count for one cache directory.
 */
export interface CacheStats {
    "extractedBytes": number;
    "extractedCount": number;
    "thumbnailBytes": number;
    "thumbnailCount": number;
    "serveBytes": number;
    "serveCount": number;

    /**
     * user asset library (ResourceRoot categories)
     */
    "resourceBytes": number;
    "resourceCount": number;
    "totalBytes": number;
}

/**
 * Config holds persistent user settings.
 */
export interface Config {
    /**
     * 配置版本号，用于迁移；0=旧配置（迁移前）
     */
    "config_version": number;
    "ui_state": UIState;

    /**
     * 迁移后清空，保留字段用于自动迁移
     */
    "library_root"?: string;

    /**
     * 总根目录
     */
    "resource_root": string;

    /**
     * "private" | "shared" (Android only)
     */
    "storage_mode": string;

    /**
     * 各类型路径覆写
     */
    "override_paths": OverridePaths;
    "blender_path": string;

    /**
     * "name_jp" | "name_en" | "filename"
     */
    "display_name_priority": string;

    /**
     * 监听目录，空则不监听
     */
    "download_watch_dir": string;

    /**
     * true 则跳过确认直接导入
     */
    "download_auto_import": boolean;

    /**
     * 监听开关（与 dir 解耦：关闭时保留 dir）
     */
    "download_watch_enabled"?: boolean;

    /**
     * 首启默认是否已应用（防重复默认覆盖用户关闭）
     */
    "download_watch_initialized"?: boolean;

    /**
     * libraryRef 数组，收藏的模型
     */
    "favorites": string[] | null;

    /**
     * 用户保存的渲染预设
     */
    "render_presets": RenderPreset[] | null;

    /**
     * MikuMikuDance 可执行文件路径，空则自动检测
     */
    "mmd_path": string;

    /**
     * 用户手动添加的软件（Managed=true）
     */
    "custom_software": SoftwareEntry[] | null;

    /**
     * libraryRef → []tag 列表
     */
    "tags": { [_ in string]?: string[] | null } | null;

    /**
     * 舞蹈套装，key = 套装 ID
     */
    "dance_sets": { [_ in string]?: DanceSet } | null;

    /**
     * libraryRef 数组，最近打开的模型（最多20条）
     */
    "recent_models": string[] | null;

    /**
     * 环境状态（天空/地面/粒子等），nil=使用前端默认
     */
    "env"?: EnvState | null;

    /**
     * 对话框最后目录记忆，优先相对路径（./前缀），详见 ADR-090
     */
    "last_dirs"?: { [_ in string]?: string } | null;
}

/**
 * DanceSet represents a dance set combining VMD motion, audio, and metadata.
 */
export interface DanceSet {
    /**
     * 套装名称
     */
    "name": string;

    /**
     * VMD 文件路径
     */
    "vmd_path": string;

    /**
     * 音频文件路径
     */
    "audio_path": string;

    /**
     * 音频偏移（秒）
     */
    "audio_offset": number;

    /**
     * 描述（可选）
     */
    "description": string;

    /**
     * 缩略图 base64（可选）
     */
    "thumbnail": string;

    /**
     * 来源库名
     */
    "source": string;
}

/**
 * EnvPresetEntry is a catalog item returned by ListEnvPresets.
 */
export interface EnvPresetEntry {
    "name": string;
    "label": string;
    "createdAt": number;
}

/**
 * EnvState stores the full environment configuration (sky, ground, particles, fog, etc.).
 */
export interface EnvState {
    "skyMode": string;
    "skyColorTop": number[];
    "skyColorMid": number[];
    "skyColorBot": number[];
    "skyTexture": string;
    "skyRotationY": number;
    "skyRotationSpeed": number;
    "skyBrightness": number;
    "starsEnabled": boolean;
    "envIntensity": number;
    "groundVisible": boolean;
    "groundType": string;
    "groundStyle": string;
    "groundColor": number[];
    "groundAlpha": number;
    "groundTexture": string;
    "groundTextureEnabled": boolean;
    "groundTextureScale": number;
    "groundTextureRotation": number;
    "groundGridSize": number;
    "groundLineColor": number[];
    "groundTerrainHeight": number;
    "groundTerrainScale": number;
    "groundTerrainSeed": number;
    "groundTerrainOctaves": number;
    "groundPitch": number;
    "groundRoll": number;
    "groundScrollSpeedX": number;
    "groundScrollSpeedZ": number;
    "groundPattern": string;
    "groundReflectionBlend": number;
    "groundReflectionQuality": string;
    "groundNormalTexture": string;
    "groundNormalStrength": number;
    "groundElevationColoring": boolean;
    "groundFollowCamera": boolean;
    "groundPbrEnabled": boolean;
    "groundProceduralTexture": string;
    "groundProceduralSeed": number;
    "groundProceduralScale": number;
    "groundRoughness": number;
    "groundMetallic": number;

    /**
     * ADR-114 Phase 2: 反射模糊 + 法线扭曲
     */
    "groundReflectionBlur": number;
    "groundReflectionDistort": number;
    "groundLevel": number;
    "groundSize": number;
    "groundEdgeFade": number;
    "windEnabled": boolean;
    "windDirection": number[];
    "windSpeed": number;
    "particleEnabled": boolean;
    "particleType": string;
    "particleEmitRate": number;
    "particleSize": number;
    "particleSpeed": number;
    "particleSplash": boolean;
    "particleCustomTexture": string;
    "waterEnabled": boolean;
    "waterLevel": number;
    "waterFlip": boolean;
    "waterColor": number[];
    "waterTransparency": number;
    "waterWaveHeight": number;
    "waterSize": number;
    "waterAnimSpeed": number;
    "foamThreshold": number;
    "foamIntensity": number;
    "foamOpacity": number;

    /**
     * 水面高级着色器参数（持久化，避免材质重建时重置）
     */
    "fresnelBias": number;
    "fresnelPower": number;
    "diffuseStrength": number;
    "ambientStrength": number;
    "foamTransitionRange": number;
    "rippleNormalStrength": number;
    "rippleGlintStrength": number;
    "causticColor1": number[];
    "causticColor2": number[];
    "causticScrollX": number;
    "causticScrollY": number;
    "fresnelAlphaInfluence": number;

    /**
     * 水面雾效（独立于全局雾）
     */
    "waterFogColor": number[];
    "waterFogDensity": number;
    "waterFogOpacityInfluence": number;

    /**
     * 水下效果
     */
    "underwaterFogDensity": number;
    "underwaterChromaticAmount": number;
    "underwaterToneIntensity": number;
    "underwaterFogMultiplier": number;
    "underwaterTintStrength": number;
    "cloudsEnabled": boolean;
    "cloudCover": number;
    "cloudScale": number;
    "cloudHeight": number;
    "cloudThickness": number;
    "cloudVisibility": number;
    "cloudGap": number;
    "debugClouds": boolean;
    "fogEnabled": boolean;
    "fogMode": string;
    "fogColor": number[];
    "fogDensity": number;
    "fogStart": number;
    "fogEnd": number;
    "collisionEnabled": boolean;
    "bodyCollisionEnabled": boolean;
    "groundCollisionEnabled": boolean;
    "sunAngle": number;
    "azimuth": number;
    "lightingPresetName"?: string | null;
    "timeOfDayActive": boolean;
    "timeOfDaySpeed": number;
}

/**
 * ExtractResult holds the result of a zip extraction.
 */
export interface ExtractResult {
    /**
     * Absolute path to extracted file (PMX or VMD)
     */
    "file_path": string;

    /**
     * Extraction root directory (for HTTP server)
     */
    "dir": string;

    /**
     * Whether cache was hit (no re-extract)
     */
    "cached": boolean;
}

/**
 * KeyBindingOverride stores a single custom key binding override.
 */
export interface KeyBindingOverride {
    "key": string;
    "ctrl"?: boolean;
    "shift"?: boolean;
    "alt"?: boolean;
}

/**
 * ModelEntry represents a model, motion, or zip entry found during library scan.
 */
export interface ModelEntry {
    /**
     * Model directory (absolute); for zip entries, the zip's directory
     */
    "dir": string;

    /**
     * file absolute path (.pmx or .vmd; also called PMXPath for historical reasons); for zip entries, the zip path
     */
    "file_path": string;

    /**
     * PMX header: local name
     */
    "name_jp": string;

    /**
     * PMX header: universal name; for VMD: basename
     */
    "name_en": string;

    /**
     * PMX header: local comment (truncated)
     */
    "comment": string;

    /**
     * Whether a thumbnail exists
     */
    "has_thumb": boolean;

    /**
     * "actor" | "motion" | "stage" | "dressing" | "bundle" | "effect" | "scene" | "other"
     */
    "type": string;

    /**
     * "pmx" | "vmd" | "zip"
     */
    "format": string;

    /**
     * "file" | "zip"
     */
    "container": string;

    /**
     * Relative path inside zip (only for container=zip)
     */
    "zip_inner": string;

    /**
     * DanceXR top-level category dir name (empty if none)
     */
    "category": string;

    /**
     * Source library name (empty for main lib)
     */
    "source": string;
}

/**
 * ModelMeta holds PMX header metadata for on-demand parsing.
 * Returned by GetModelMeta / GetModelMetaBatch.
 */
export interface ModelMeta {
    "name_jp": string;
    "name_en": string;

    /**
     * PMX header: local comment (truncated)
     */
    "comment": string;
}

/**
 * ModelPresetEntry is a listing entry for a model preset in the library.
 */
export interface ModelPresetEntry {
    "name": string;
    "presetName": string;
    "modelName": string;
    "modelRef": string;
    "updatedAt": number;
    "autoApply": boolean;
}

/**
 * OverridePaths allows per-category path overrides.
 * If a field is empty, the default path under ResourceRoot is used.
 */
export interface OverridePaths {
    /**
     * 默认 resource_root/PMX
     */
    "pmx": string;

    /**
     * 默认 resource_root/VMD
     */
    "vmd": string;

    /**
     * 默认 resource_root/audio
     */
    "audio": string;

    /**
     * 默认 resource_root/stage
     */
    "stage": string;

    /**
     * 默认 resource_root/prop
     */
    "prop": string;

    /**
     * 默认 resource_root/environment
     */
    "environment": string;

    /**
     * 默认 resource_root/MD-dress
     */
    "md_dress": string;

    /**
     * 默认 resource_root/setting
     */
    "setting": string;
}

/**
 * PlazaDownloadResult is the return type for DownloadFromPlaza.
 */
export interface PlazaDownloadResult {
    "filePath": string;
    "size": number;
    "fileName": string;
}

/**
 * RenderPreset stores a user-defined rendering preset.
 */
export interface RenderPreset {
    "name": string;

    /**
     * RenderState fields as flat key-value pairs
     */
    "params": { [_ in string]?: any } | null;
}

/**
 * SoftwareEntry represents an executable found in the software/ directory or user-added.
 */
export interface SoftwareEntry {
    /**
     * Display name (without extension)
     */
    "name": string;

    /**
     * Full absolute path
     */
    "path": string;

    /**
     * "blender" | "mmd" | "pmxeditor" | "other"
     */
    "kind": string;

    /**
     * Command-line template, supports {model} placeholder
     */
    "args": string;

    /**
     * true=Config-persisted custom entry, false=scanned from software/
     */
    "managed": boolean;

    /**
     * Reserved for future .exe icon extraction
     */
    "icon": string;
}

/**
 * UIState stores user-customizable UI preferences.
 */
export interface UIState {
    /**
     * 0.8~1.3, default 1.0
     */
    "scale": number;

    /**
     * 220~380, default 280
     */
    "popupWidth": number;

    /**
     * hex, default "#4a6cf7"
     */
    "accent": string;

    /**
     * "system"|"noto"|"yahei"
     */
    "fontFamily": string;

    /**
     * enable menu slide animations
     */
    "animations": boolean;

    /**
     * enable background blur on overlays
     */
    "blurBg": boolean;

    /**
     * "auto"|"quality"|"balanced"|"performance"
     */
    "performanceMode": string;
    "screenshotFormat": string;
    "screenshotQuality": number;
    "screenshotDir"?: string;

    /**
     * 缩略图分辨率（最长边 px），0=默认 512
     */
    "thumbnailResolution"?: number;
    "autoCameraEnabled": boolean;
    "autoCameraBeatsPerSwitch": number;
    "autoUpdateEnabled": boolean;

    /**
     * --- 以下字段原为前端会话级，2026-07-07 新增持久化支持 ---
     * 帧率上限；0=不限
     */
    "fpsLimit"?: number;

    /**
     * 垂直同步（默认 true）
     */
    "vsync"?: boolean;

    /**
     * 新加载 actor 默认物理开关
     */
    "defaultPhysicsEnabled"?: boolean;

    /**
     * 渲染分辨率缩放；1.0=原生
     */
    "renderScale"?: number;

    /**
     * 相机灵敏度倍数；1.0=默认
     */
    "cameraSensitivity"?: number;

    /**
     * 反转 Y 轴
     */
    "invertYAxis"?: boolean;

    /**
     * 新加载模型自动缩放
     */
    "autoScaleModel"?: boolean;

    /**
     * 新加载模型自动居中取景（相机对准模型）
     */
    "autoCenterModel"?: boolean;

    /**
     * 材质分类映射
     */
    "materialCategoryMap"?: { [_ in string]?: string } | null;

    /**
     * [doc:adr-066] 资源库视图模式："list"|"grid"
     */
    "resourceViewMode"?: string;

    /**
     * --- 音频设置（持久化，避免重启后重置） ---
     * 默认音量 0-1
     */
    "volume"?: number;

    /**
     * 音频偏移（秒）
     */
    "audioOffset"?: number;

    /**
     * BPM 量化开关
     */
    "bpmQuantizeEnabled"?: boolean;

    /**
     * 自动加载伴音
     */
    "autoLoadCompanionAudio"?: boolean;

    /**
     * SFX 开关
     */
    "sfxEnabled"?: boolean;

    /**
     * SFX 音量 0-1
     */
    "sfxVolume"?: number;

    /**
     * 脚步声开关
     */
    "footstepEnabled"?: boolean;

    /**
     * 脚步声音量 0-1
     */
    "footstepVolume"?: number;

    /**
     * --- 快捷键自定义绑定 ---
     * 自定义快捷键覆盖
     */
    "keyBindings"?: { [_ in string]?: KeyBindingOverride } | null;

    /**
     * --- 顶部 HUD 显隐开关（2026-07-14 新增）---
     * 使用指针以区分「未设置（nil→默认显示）」与「显式关闭（false）」，确保关闭状态可持久化。
     * 帧率时钟 HUD 显隐；nil=显示
     */
    "showFpsClock"?: boolean | null;

    /**
     * 多线程（MPR/SPR）徽标 HUD 显隐；nil=显示
     */
    "showRuntimeBadge"?: boolean | null;
}

/**
 * UpdateCheckResult holds the outcome of a version check.
 */
export interface UpdateCheckResult {
    "current": string;
    "latest": string;
    "available": boolean;
    "url": string;
    "checkedAt": number;

    /**
     * Error carries network/parse failures. A non-empty Error means the check
     * could not be completed; the UI degrades gracefully rather than treating
     * this as a hard failure.
     */
    "error"?: string;
}
