// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExternalPath(arg1) {
  return window['go']['main']['App']['AddExternalPath'](arg1);
}

export function AddRecentModel(arg1) {
  return window['go']['main']['App']['AddRecentModel'](arg1);
}

export function AddTag(arg1, arg2) {
  return window['go']['main']['App']['AddTag'](arg1, arg2);
}

export function AutoDetectMMD() {
  return window['go']['main']['App']['AutoDetectMMD']();
}

export function CleanOrphanCache() {
  return window['go']['main']['App']['CleanOrphanCache']();
}

export function ClearExtractCache() {
  return window['go']['main']['App']['ClearExtractCache']();
}

export function DeleteDanceSet(arg1) {
  return window['go']['main']['App']['DeleteDanceSet'](arg1);
}

export function DeletePresetScene(arg1) {
  return window['go']['main']['App']['DeletePresetScene'](arg1);
}

export function DeleteRenderPreset(arg1) {
  return window['go']['main']['App']['DeleteRenderPreset'](arg1);
}

export function ExtractZip(arg1, arg2) {
  return window['go']['main']['App']['ExtractZip'](arg1, arg2);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDanceSets() {
  return window['go']['main']['App']['GetDanceSets']();
}

export function GetDownloadWatchStatus() {
  return window['go']['main']['App']['GetDownloadWatchStatus']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetLibraryIndex() {
  return window['go']['main']['App']['GetLibraryIndex']();
}

export function GetModelMeta(arg1) {
  return window['go']['main']['App']['GetModelMeta'](arg1);
}

export function GetModelMetaBatch(arg1) {
  return window['go']['main']['App']['GetModelMetaBatch'](arg1);
}

export function GetModelsByTag(arg1) {
  return window['go']['main']['App']['GetModelsByTag'](arg1);
}

export function GetPresetScenes() {
  return window['go']['main']['App']['GetPresetScenes']();
}

export function GetPresetScenesDir() {
  return window['go']['main']['App']['GetPresetScenesDir']();
}

export function GetRecentModels() {
  return window['go']['main']['App']['GetRecentModels']();
}

export function GetRenderPresets() {
  return window['go']['main']['App']['GetRenderPresets']();
}

export function GetTagsByModel(arg1) {
  return window['go']['main']['App']['GetTagsByModel'](arg1);
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetThumbnailBatch(arg1) {
  return window['go']['main']['App']['GetThumbnailBatch'](arg1);
}

export function ImportDanceSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportDanceSet'](arg1, arg2, arg3);
}

export function ImportLocalFile(arg1) {
  return window['go']['main']['App']['ImportLocalFile'](arg1);
}

export function ImportZip(arg1) {
  return window['go']['main']['App']['ImportZip'](arg1);
}

export function IsolateModelDir(arg1) {
  return window['go']['main']['App']['IsolateModelDir'](arg1);
}

export function LaunchSoftware(arg1) {
  return window['go']['main']['App']['LaunchSoftware'](arg1);
}

export function LoadLastScene() {
  return window['go']['main']['App']['LoadLastScene']();
}

export function LoadModelPreset(arg1) {
  return window['go']['main']['App']['LoadModelPreset'](arg1);
}

export function LoadSceneFile(arg1) {
  return window['go']['main']['App']['LoadSceneFile'](arg1);
}

export function OpenInBlender(arg1) {
  return window['go']['main']['App']['OpenInBlender'](arg1);
}

export function OpenInMMD(arg1) {
  return window['go']['main']['App']['OpenInMMD'](arg1);
}

export function OpenSoftwareDir() {
  return window['go']['main']['App']['OpenSoftwareDir']();
}

export function RemoveExternalPath(arg1) {
  return window['go']['main']['App']['RemoveExternalPath'](arg1);
}

export function RemoveTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveTag'](arg1, arg2);
}

export function RenameExternalPath(arg1, arg2) {
  return window['go']['main']['App']['RenameExternalPath'](arg1, arg2);
}

export function SaveDanceSet(arg1, arg2) {
  return window['go']['main']['App']['SaveDanceSet'](arg1, arg2);
}

export function SaveLastScene(arg1) {
  return window['go']['main']['App']['SaveLastScene'](arg1);
}

export function SaveModelPreset(arg1, arg2) {
  return window['go']['main']['App']['SaveModelPreset'](arg1, arg2);
}

export function SaveRenderPreset(arg1, arg2) {
  return window['go']['main']['App']['SaveRenderPreset'](arg1, arg2);
}

export function SaveSceneFile(arg1, arg2) {
  return window['go']['main']['App']['SaveSceneFile'](arg1, arg2);
}

export function SaveScenePreset(arg1) {
  return window['go']['main']['App']['SaveScenePreset'](arg1);
}

export function SaveScreenshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveScreenshot'](arg1, arg2, arg3);
}

export function SaveThumbnail(arg1, arg2) {
  return window['go']['main']['App']['SaveThumbnail'](arg1, arg2);
}

export function ScanModelDir(arg1, arg2) {
  return window['go']['main']['App']['ScanModelDir'](arg1, arg2);
}

export function ScanSoftwareDir() {
  return window['go']['main']['App']['ScanSoftwareDir']();
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function SelectExeFile() {
  return window['go']['main']['App']['SelectExeFile']();
}

export function SelectPMXFile() {
  return window['go']['main']['App']['SelectPMXFile']();
}

export function SelectPresetOpenFile() {
  return window['go']['main']['App']['SelectPresetOpenFile']();
}

export function SelectPresetSaveFile() {
  return window['go']['main']['App']['SelectPresetSaveFile']();
}

export function SelectSceneOpenFile() {
  return window['go']['main']['App']['SelectSceneOpenFile']();
}

export function SelectSceneSaveFile() {
  return window['go']['main']['App']['SelectSceneSaveFile']();
}

export function SelectVMDMotion() {
  return window['go']['main']['App']['SelectVMDMotion']();
}

export function SelectVPDPose() {
  return window['go']['main']['App']['SelectVPDPose']();
}

export function SetBlenderPath(arg1) {
  return window['go']['main']['App']['SetBlenderPath'](arg1);
}

export function SetDisplayNamePriority(arg1) {
  return window['go']['main']['App']['SetDisplayNamePriority'](arg1);
}

export function SetDownloadAutoImport(arg1) {
  return window['go']['main']['App']['SetDownloadAutoImport'](arg1);
}

export function SetDownloadWatchDir(arg1) {
  return window['go']['main']['App']['SetDownloadWatchDir'](arg1);
}

export function SetEnvState(arg1) {
  return window['go']['main']['App']['SetEnvState'](arg1);
}

export function SetLibraryRoot(arg1) {
  return window['go']['main']['App']['SetLibraryRoot'](arg1);
}

export function SetMMDPath(arg1) {
  return window['go']['main']['App']['SetMMDPath'](arg1);
}

export function StartFileServer(arg1) {
  return window['go']['main']['App']['StartFileServer'](arg1);
}

export function StartWatchDir(arg1) {
  return window['go']['main']['App']['StartWatchDir'](arg1);
}

export function StopFileServer(arg1) {
  return window['go']['main']['App']['StopFileServer'](arg1);
}

export function StopWatchDir() {
  return window['go']['main']['App']['StopWatchDir']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
