// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddExternalPath(arg1:string):Promise<void>;

export function CleanOrphanCache():Promise<number>;

export function ClearExtractCache():Promise<void>;

export function ExtractZip(arg1:string,arg2:string):Promise<main.ExtractResult>;

export function GetConfig():Promise<main.Config>;

export function GetLibraryIndex():Promise<Array<main.ModelEntry>>;

export function GetModelMeta(arg1:string):Promise<main.ModelMeta>;

export function GetModelMetaBatch(arg1:Array<string>):Promise<Record<string, main.ModelMeta>>;

export function GetThumbnail(arg1:string):Promise<string>;

export function GetThumbnailBatch(arg1:Array<string>):Promise<Record<string, string>>;

export function ImportZip(arg1:string):Promise<main.ExtractResult>;

export function IsolateModelDir(arg1:string):Promise<string>;

export function LoadLastScene():Promise<string>;

export function LoadSceneFile(arg1:string):Promise<string>;

export function OpenInBlender(arg1:string):Promise<void>;

export function RemoveExternalPath(arg1:string):Promise<void>;

export function RenameExternalPath(arg1:string,arg2:string):Promise<void>;

export function SaveLastScene(arg1:string):Promise<void>;

export function SaveSceneFile(arg1:string,arg2:string):Promise<void>;

export function SaveThumbnail(arg1:string,arg2:string):Promise<void>;

export function ScanModelDir(arg1:string,arg2:Array<main.ExternalPath>):Promise<Array<main.ModelEntry>>;

export function SelectDir():Promise<string>;

export function SelectPMXFile():Promise<string>;

export function SelectSceneOpenFile():Promise<string>;

export function SelectSceneSaveFile():Promise<string>;

export function SelectVMDMotion():Promise<string>;

export function SetBlenderPath(arg1:string):Promise<void>;

export function SetDisplayNamePriority(arg1:string):Promise<void>;

export function SetLibraryRoot(arg1:string):Promise<void>;

export function StartFileServer(arg1:string):Promise<number>;

export function StopFileServer(arg1:string):Promise<void>;
