// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExternalPath(arg1) {
  return window['go']['main']['App']['AddExternalPath'](arg1);
}

export function CleanOrphanCache() {
  return window['go']['main']['App']['CleanOrphanCache']();
}

export function ClearExtractCache() {
  return window['go']['main']['App']['ClearExtractCache']();
}

export function ExtractZip(arg1, arg2) {
  return window['go']['main']['App']['ExtractZip'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLibraryIndex() {
  return window['go']['main']['App']['GetLibraryIndex']();
}

export function GetModelMeta(arg1) {
  return window['go']['main']['App']['GetModelMeta'](arg1);
}

export function GetModelMetaBatch(arg1) {
  return window['go']['main']['App']['GetModelMetaBatch'](arg1);
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetThumbnailBatch(arg1) {
  return window['go']['main']['App']['GetThumbnailBatch'](arg1);
}

export function ImportZip(arg1) {
  return window['go']['main']['App']['ImportZip'](arg1);
}

export function IsolateModelDir(arg1) {
  return window['go']['main']['App']['IsolateModelDir'](arg1);
}

export function LoadLastScene() {
  return window['go']['main']['App']['LoadLastScene']();
}

export function LoadSceneFile(arg1) {
  return window['go']['main']['App']['LoadSceneFile'](arg1);
}

export function OpenInBlender(arg1) {
  return window['go']['main']['App']['OpenInBlender'](arg1);
}

export function RemoveExternalPath(arg1) {
  return window['go']['main']['App']['RemoveExternalPath'](arg1);
}

export function RenameExternalPath(arg1, arg2) {
  return window['go']['main']['App']['RenameExternalPath'](arg1, arg2);
}

export function SaveLastScene(arg1) {
  return window['go']['main']['App']['SaveLastScene'](arg1);
}

export function SaveSceneFile(arg1, arg2) {
  return window['go']['main']['App']['SaveSceneFile'](arg1, arg2);
}

export function SaveThumbnail(arg1, arg2) {
  return window['go']['main']['App']['SaveThumbnail'](arg1, arg2);
}

export function ScanModelDir(arg1, arg2) {
  return window['go']['main']['App']['ScanModelDir'](arg1, arg2);
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function SelectPMXFile() {
  return window['go']['main']['App']['SelectPMXFile']();
}

export function SelectSceneOpenFile() {
  return window['go']['main']['App']['SelectSceneOpenFile']();
}

export function SelectSceneSaveFile() {
  return window['go']['main']['App']['SelectSceneSaveFile']();
}

export function SelectVMDMotion() {
  return window['go']['main']['App']['SelectVMDMotion']();
}

export function SetBlenderPath(arg1) {
  return window['go']['main']['App']['SetBlenderPath'](arg1);
}

export function SetDisplayNamePriority(arg1) {
  return window['go']['main']['App']['SetDisplayNamePriority'](arg1);
}

export function SetLibraryRoot(arg1) {
  return window['go']['main']['App']['SetLibraryRoot'](arg1);
}

export function StartFileServer(arg1) {
  return window['go']['main']['App']['StartFileServer'](arg1);
}

export function StopFileServer(arg1) {
  return window['go']['main']['App']['StopFileServer'](arg1);
}
