// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCustomSoftware adds a user-defined software entry to the config.
 */
export function AddCustomSoftware(path: string, name: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(2861093638, path, name, args);
}

/**
 * AddExternalPath adds an external library path with auto-generated basename name, triggers rescan+reindex.
 */
export function AddExternalPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(918366732, path);
}

/**
 * AddRecentModel pushes a libraryRef to the top of the recent models list.
 * If already present, it is moved to the top. List is capped at maxRecentModels.
 */
export function AddRecentModel(libraryRef: string): $CancellablePromise<void> {
    return $Call.ByID(1020741284, libraryRef);
}

/**
 * AddTag adds a tag to a model identified by its libraryRef.
 */
export function AddTag(libraryRef: string, tag: string): $CancellablePromise<void> {
    return $Call.ByID(3086463204, libraryRef, tag);
}

/**
 * AutoDetectMMD searches for MMD in common install paths and saves the result.
 * Returns the detected path, or an error if not found.
 */
export function AutoDetectMMD(): $CancellablePromise<string> {
    return $Call.ByID(4206549781);
}

/**
 * CleanOrphanCache cleans extraction cache whose source zip no longer exists.
 */
export function CleanOrphanCache(): $CancellablePromise<number> {
    return $Call.ByID(2313460938);
}

/**
 * ClearExtractCache removes ALL extraction cache directories, forcing
 * re-extraction on the next model load (with current encoding fixes).
 */
export function ClearExtractCache(): $CancellablePromise<void> {
    return $Call.ByID(3291925779);
}

/**
 * ClearThumbnailCache removes ALL thumbnail cache files, forcing
 * re-generation on the next model load.
 */
export function ClearThumbnailCache(): $CancellablePromise<void> {
    return $Call.ByID(3775367792);
}

/**
 * DeleteDanceSet deletes a dance set by id.
 */
export function DeleteDanceSet(id: string): $CancellablePromise<void> {
    return $Call.ByID(1235675635, id);
}

/**
 * DeleteEnvPreset removes a .env file by name.
 */
export function DeleteEnvPreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(422211230, name);
}

/**
 * DeleteModelPreset removes a named model preset from the library.
 */
export function DeleteModelPreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(2022062760, name);
}

/**
 * DeletePresetScene deletes a named preset scene file.
 */
export function DeletePresetScene(name: string): $CancellablePromise<void> {
    return $Call.ByID(2560348263, name);
}

/**
 * DeleteRenderPreset removes a named render preset.
 */
export function DeleteRenderPreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(787959061, name);
}

/**
 * ExtractZip extracts a zip file to the cache directory and returns the path
 * to the extracted PMX file specified by innerPath.
 * 
 * Cache hit: if the source zip's mtime and size haven't changed since last
 * extraction, returns the cached path immediately (Cached=true).
 * 
 * Cache miss: removes the old cache directory, re-extracts the entire zip,
 * writes a manifest.json, and returns the extracted path (Cached=false).
 * 
 * Zip slip protection: validates that every extracted entry stays within the
 * destination directory.
 */
export function ExtractZip(zipPath: string, innerPath: string): $CancellablePromise<$models.ExtractResult | null> {
    return $Call.ByID(3681970325, zipPath, innerPath);
}

/**
 * GetAllTags returns a deduplicated list of all tags across all models.
 */
export function GetAllTags(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2819596067);
}

/**
 * GetConfig reads the persisted config from disk.
 * Returns an empty Config (no error) if file doesn't exist.
 * Real I/O errors (permission, filesystem) are logged via safeLogError.
 */
export function GetConfig(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(1200034045);
}

/**
 * GetDanceSets returns all dance sets.
 */
export function GetDanceSets(): $CancellablePromise<$models.DanceSet[] | null> {
    return $Call.ByID(1887868363);
}

/**
 * GetDownloadWatchStatus returns the current watch state (directory being watched or empty string).
 */
export function GetDownloadWatchStatus(): $CancellablePromise<string> {
    return $Call.ByID(2772039140);
}

/**
 * GetFavorites returns the current favorites list.
 * Reads from the built-in tag "收藏" in the tag system.
 */
export function GetFavorites(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1693347796);
}

/**
 * GetLibraryIndex reads the last scanned index from disk.
 */
export function GetLibraryIndex(): $CancellablePromise<$models.ModelEntry[] | null> {
    return $Call.ByID(4237313254);
}

/**
 * GetModelMeta parses the PMX header for a single PMX file and returns its metadata.
 * Returns empty meta on error (non-fatal), logs real errors.
 */
export function GetModelMeta(pmxPath: string): $CancellablePromise<$models.ModelMeta> {
    return $Call.ByID(114694905, pmxPath);
}

/**
 * GetModelMetaBatch parses PMX headers for multiple PMX files at once.
 * Returns a map keyed by pmxPath, with empty meta for unparseable files.
 */
export function GetModelMetaBatch(paths: string[] | null): $CancellablePromise<{ [_ in string]?: $models.ModelMeta } | null> {
    return $Call.ByID(2469872863, paths);
}

/**
 * GetModelPresets lists all .mcupreset.json files in the model presets directory.
 */
export function GetModelPresets(): $CancellablePromise<$models.ModelPresetEntry[] | null> {
    return $Call.ByID(1386626400);
}

/**
 * GetModelsByTag returns all libraryRefs that have a specific tag.
 */
export function GetModelsByTag(tag: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(575737252, tag);
}

/**
 * GetPresetScenes lists numbered .mmascene files in the scene presets directory.
 */
export function GetPresetScenes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(371590025);
}

/**
 * GetPresetScenesDir returns the absolute path of the scene presets directory.
 */
export function GetPresetScenesDir(): $CancellablePromise<string> {
    return $Call.ByID(2052679320);
}

/**
 * GetRecentModels returns the recently opened model libraryRefs (newest first).
 */
export function GetRecentModels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1350627662);
}

/**
 * GetRenderPresets returns all user-defined render presets.
 */
export function GetRenderPresets(): $CancellablePromise<$models.RenderPreset[] | null> {
    return $Call.ByID(1563979189);
}

/**
 * GetTagsByModel returns the tags for a specific model.
 */
export function GetTagsByModel(libraryRef: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3524036824, libraryRef);
}

/**
 * GetThumbnail returns a base64-encoded PNG thumbnail for the given model path.
 */
export function GetThumbnail(modelPath: string): $CancellablePromise<string> {
    return $Call.ByID(1359847941, modelPath);
}

/**
 * GetThumbnailBatch returns thumbnails for multiple model paths at once.
 */
export function GetThumbnailBatch(paths: string[] | null): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2694629595, paths);
}

/**
 * ImportDanceSet creates a dance set from a VMD file and audio file.
 * Returns the generated dance set id.
 */
export function ImportDanceSet(vmdPath: string, audioPath: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1794370737, vmdPath, audioPath, name);
}

/**
 * ImportLocalFile imports a local file into the model library.
 * For .zip files, it finds the first .pmx inside and extracts via ImportZip.
 * For .pmx/.vmd files, it returns the path directly as an ExtractResult.
 */
export function ImportLocalFile(path: string): $CancellablePromise<$models.ExtractResult | null> {
    return $Call.ByID(2791227369, path);
}

/**
 * ImportZip opens a zip file, finds the first .pmx entry, and extracts via ExtractZip.
 * Returns *ExtractResult as a convenience for the frontend import flow.
 */
export function ImportZip(zipPath: string): $CancellablePromise<$models.ExtractResult | null> {
    return $Call.ByID(3600146931, zipPath);
}

/**
 * IsolateModelDir ensures the model file is served from a safe directory.
 * [doc:architecture] IsolateModelDir — 安全隔离：信任目录返回原目录，外部文件复制到 temp
 * 规范文档: docs/architecture.md §数据通道（HTTP 文件服务）
 * For files inside trusted roots, returns the original directory unchanged.
 * For external files, copies PMX + all siblings to a temp directory.
 */
export function IsolateModelDir(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(4269909270, filePath);
}

/**
 * LaunchSoftware starts an executable by path with optional command-line arguments.
 * The args string is split into arguments and passed to the executable.
 */
export function LaunchSoftware(path: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(4168994863, path, args);
}

/**
 * ListEnvPresets returns all user-saved env presets in the presets directory.
 */
export function ListEnvPresets(): $CancellablePromise<$models.EnvPresetEntry[] | null> {
    return $Call.ByID(2979072796);
}

/**
 * ListSubDirs returns first-level subdirectory names under the given directory.
 */
export function ListSubDirs(dirPath: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3419087809, dirPath);
}

/**
 * LoadEnvPreset reads a .env JSON file by name.
 */
export function LoadEnvPreset(name: string): $CancellablePromise<string> {
    return $Call.ByID(2202599535, name);
}

/**
 * LoadLastScene reads the auto-saved scene state.
 */
export function LoadLastScene(): $CancellablePromise<string> {
    return $Call.ByID(1128042995);
}

/**
 * LoadModelPreset reads a JSON model preset file from the given path.
 */
export function LoadModelPreset(path: string): $CancellablePromise<string> {
    return $Call.ByID(2754468149, path);
}

/**
 * LoadModelPresetFromLib reads a model preset JSON from the library by name.
 */
export function LoadModelPresetFromLib(name: string): $CancellablePromise<string> {
    return $Call.ByID(3769717036, name);
}

/**
 * LoadOutfitFile reads <modelDir>/outfits.json. Returns empty string if not found.
 */
export function LoadOutfitFile(pmxPath: string): $CancellablePromise<string> {
    return $Call.ByID(2438898604, pmxPath);
}

/**
 * LoadSceneFile reads a JSON scene file from the given path.
 */
export function LoadSceneFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(881461809, path);
}

/**
 * OpenInBlender launches Blender and opens the specified model file.
 */
export function OpenInBlender(modelPath: string): $CancellablePromise<void> {
    return $Call.ByID(685561090, modelPath);
}

/**
 * OpenInMMD launches MikuMikuDance and opens the specified model file.
 */
export function OpenInMMD(modelPath: string): $CancellablePromise<void> {
    return $Call.ByID(973262636, modelPath);
}

/**
 * OpenSoftwareDir opens the software directory in the system file manager.
 */
export function OpenSoftwareDir(): $CancellablePromise<void> {
    return $Call.ByID(2725415723);
}

/**
 * OpenWithSoftware opens a model file with the specified software, replacing {model}
 * in the args template with the model path.
 * Each {model} token is replaced individually so paths with spaces stay as a single argv.
 */
export function OpenWithSoftware(modelPath: string, softwarePath: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(3970281424, modelPath, softwarePath, args);
}

/**
 * RemoveCustomSoftware removes a user-defined software entry from the config by path.
 */
export function RemoveCustomSoftware(path: string): $CancellablePromise<void> {
    return $Call.ByID(2348454783, path);
}

/**
 * RemoveExternalPath removes an external library by path, triggers rescan+reindex.
 */
export function RemoveExternalPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1144146553, path);
}

/**
 * RemoveTag removes a tag from a model.
 */
export function RemoveTag(libraryRef: string, tag: string): $CancellablePromise<void> {
    return $Call.ByID(3348484979, libraryRef, tag);
}

/**
 * RenameExternalPath renames an external library display name.
 */
export function RenameExternalPath(path: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3410361247, path, name);
}

/**
 * RenameModelPreset renames a model preset in the library.
 */
export function RenameModelPreset(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2610495111, oldName, newName);
}

/**
 * SaveDanceSet saves or updates a dance set with the given id.
 */
export function SaveDanceSet(id: string, ds: $models.DanceSet): $CancellablePromise<void> {
    return $Call.ByID(3712782717, id, ds);
}

/**
 * SaveEnvPreset writes a .env JSON file under env-presets/<name>.env.
 * The name is sanitized; the JSON content is the caller's responsibility.
 */
export function SaveEnvPreset(name: string, jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(3128969768, name, jsonStr);
}

/**
 * SaveLastScene stores the current scene state for auto-recovery on next launch.
 */
export function SaveLastScene(jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(3762107560, jsonStr);
}

/**
 * SaveModelPreset writes a JSON model preset file to the given path.
 */
export function SaveModelPreset(jsonStr: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3582272534, jsonStr, path);
}

/**
 * SaveModelPresetToLib saves a model preset JSON to the library with the given name.
 */
export function SaveModelPresetToLib(name: string, jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(3471238194, name, jsonStr);
}

/**
 * SaveRenderPreset saves or updates a named render preset.
 * params is a JSON string of the RenderState fields.
 */
export function SaveRenderPreset(name: string, params: string): $CancellablePromise<void> {
    return $Call.ByID(1945881039, name, params);
}

/**
 * SaveSceneFile writes a JSON scene file to the given path.
 */
export function SaveSceneFile(jsonStr: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(128830030, jsonStr, path);
}

/**
 * SaveScenePreset saves a scene JSON as an auto-numbered .mmascene in the presets directory.
 * Returns the generated filename (e.g. "003.mmascene").
 */
export function SaveScenePreset(jsonStr: string): $CancellablePromise<string> {
    return $Call.ByID(49006279, jsonStr);
}

/**
 * SaveScreenshot saves a base64-encoded PNG screenshot to the specified directory.
 */
export function SaveScreenshot(dir: string, filename: string, base64PNG: string): $CancellablePromise<void> {
    return $Call.ByID(3143230836, dir, filename, base64PNG);
}

/**
 * SaveThumbnail saves a base64-encoded PNG thumbnail for the given model path.
 */
export function SaveThumbnail(modelPath: string, base64PNG: string): $CancellablePromise<void> {
    return $Call.ByID(3187703724, modelPath, base64PNG);
}

/**
 * ScanModelDir scans main root + all external paths and returns merged ModelEntry list.
 * Main root entries have Source=""; external entries get Source = ep.Name.
 * root may be "" (external-only scan); external may be nil (main-only scan).
 */
export function ScanModelDir(root: string, external: $models.ExternalPath[] | null): $CancellablePromise<$models.ModelEntry[] | null> {
    return $Call.ByID(4136341212, root, external);
}

/**
 * ScanSoftwareDir scans the software/ directory for .exe files, merges with user-added
 * custom software from config, and returns the combined list (deduplicated by path).
 */
export function ScanSoftwareDir(): $CancellablePromise<$models.SoftwareEntry[] | null> {
    return $Call.ByID(2051734052);
}

/**
 * SelectAudioFile opens a file dialog to select an audio file
 */
export function SelectAudioFile(): $CancellablePromise<string> {
    return $Call.ByID(704377791);
}

/**
 * SelectDir opens a directory picker dialog.
 */
export function SelectDir(): $CancellablePromise<string> {
    return $Call.ByID(3953379924);
}

/**
 * SelectEnvTextureFile opens a file dialog to select an environment/skybox texture.
 */
export function SelectEnvTextureFile(): $CancellablePromise<string> {
    return $Call.ByID(564497185);
}

/**
 * SelectExeFile opens a file dialog to select an executable file.
 */
export function SelectExeFile(): $CancellablePromise<string> {
    return $Call.ByID(3285660073);
}

/**
 * SelectPMXFile opens a file dialog to select a PMX file
 */
export function SelectPMXFile(): $CancellablePromise<string> {
    return $Call.ByID(571650396);
}

/**
 * SelectPresetOpenFile opens a file dialog to pick a model preset file.
 */
export function SelectPresetOpenFile(): $CancellablePromise<string> {
    return $Call.ByID(1482029880);
}

/**
 * SelectPresetSaveFile opens a save dialog for model preset files.
 */
export function SelectPresetSaveFile(): $CancellablePromise<string> {
    return $Call.ByID(1337349589);
}

/**
 * SelectSceneOpenFile opens a file dialog to pick a scene file.
 */
export function SelectSceneOpenFile(): $CancellablePromise<string> {
    return $Call.ByID(2898754769);
}

/**
 * SelectSceneSaveFile opens a save dialog for scene files.
 */
export function SelectSceneSaveFile(): $CancellablePromise<string> {
    return $Call.ByID(2908027304);
}

/**
 * SelectVMDMotion opens a file dialog to select a VMD motion file
 */
export function SelectVMDMotion(): $CancellablePromise<string> {
    return $Call.ByID(155980554);
}

/**
 * SelectVPDPose opens a file dialog to select a VPD pose file
 */
export function SelectVPDPose(): $CancellablePromise<string> {
    return $Call.ByID(3510948092);
}

/**
 * SetBlenderPath saves the Blender executable path to config.
 */
export function SetBlenderPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3260295182, path);
}

/**
 * SetDisplayNamePriority persists the display name priority setting.
 */
export function SetDisplayNamePriority(priority: string): $CancellablePromise<void> {
    return $Call.ByID(329006248, priority);
}

/**
 * SetDownloadAutoImport persists the auto-import preference to config.
 */
export function SetDownloadAutoImport(auto: boolean): $CancellablePromise<void> {
    return $Call.ByID(3202075281, auto);
}

/**
 * SetDownloadWatchDir persists the download watch directory to config
 * and restarts the watcher (if dir is non-empty) or stops it (if dir is empty).
 */
export function SetDownloadWatchDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(3212321213, dir);
}

/**
 * SetEnvState persists the environment state (sky, ground, particles, fog, etc.).
 */
export function SetEnvState(env: $models.EnvState): $CancellablePromise<void> {
    return $Call.ByID(1570109571, env);
}

/**
 * SetLibraryRoot persists the library root path (preserving external paths) and triggers a rescan+reindex.
 */
export function SetLibraryRoot(root: string): $CancellablePromise<void> {
    return $Call.ByID(1400520186, root);
}

/**
 * SetMMDPath saves the MMD executable path to config.
 * If path is empty, automatically detects MMD from common install locations.
 */
export function SetMMDPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(128922700, path);
}

/**
 * SetPerformanceMode persists the performance mode setting.
 */
export function SetPerformanceMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(1733963968, mode);
}

/**
 * SetUIAccent persists the accent color hex.
 */
export function SetUIAccent(hex: string): $CancellablePromise<void> {
    return $Call.ByID(672661955, hex);
}

/**
 * SetUIAnimations enables or disables menu slide animations.
 */
export function SetUIAnimations(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3141689350, on);
}

/**
 * SetUIBlurBg enables or disables background blur on overlays.
 */
export function SetUIBlurBg(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3711776551, on);
}

/**
 * SetUIFontFamily persists the font family key ("system"|"noto"|"yahei").
 */
export function SetUIFontFamily(key: string): $CancellablePromise<void> {
    return $Call.ByID(1283662892, key);
}

/**
 * SetUIPopupWidth persists the popup width.
 */
export function SetUIPopupWidth(width: number): $CancellablePromise<void> {
    return $Call.ByID(199913523, width);
}

/**
 * SetUIScale persists the UI scale factor.
 */
export function SetUIScale(scale: number): $CancellablePromise<void> {
    return $Call.ByID(1360941901, scale);
}

/**
 * StartFileServer starts (or reuses) an HTTP file server for dirPath,
 * serving files with basename fallback for texture lookup.
 * Multiple directories each get their own port; servers are never killed
 * until the app shuts down.
 */
export function StartFileServer(dirPath: string): $CancellablePromise<number> {
    return $Call.ByID(1633413518, dirPath);
}

/**
 * StartWatchDir starts fsnotify-based watching on the specified directory.
 * If already watching a directory, it stops the previous watcher first.
 * Only files with .zip/.pmx/.vmd extensions trigger notifications,
 * filtered through Magic Number detection to skip incomplete downloads.
 */
export function StartWatchDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2141650213, dir);
}

/**
 * StopFileServer shuts down the HTTP file server for the given directory.
 * Maintained for future cleanup use (e.g., scene teardown, directory unmount).
 * Currently unused by the frontend — HTTP servers run until app exit.
 */
export function StopFileServer(dirPath: string): $CancellablePromise<void> {
    return $Call.ByID(1777788024, dirPath);
}

/**
 * StopWatchDir stops the current directory watcher.
 */
export function StopWatchDir(): $CancellablePromise<void> {
    return $Call.ByID(1278233751);
}

/**
 * ToggleFavorite adds or removes a libraryRef from the favorites list.
 * Favorites are stored as the built-in tag "收藏" in the tag system.
 */
export function ToggleFavorite(libraryRef: string): $CancellablePromise<void> {
    return $Call.ByID(1319626997, libraryRef);
}

/**
 * UpdateCustomSoftware updates name and args for an existing custom software entry.
 */
export function UpdateCustomSoftware(path: string, name: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(3165409398, path, name, args);
}
